![Ironhack Logo](https://i.imgur.com/1QgrNNw.png)

In [82]:

from sqlalchemy import create_engine 
import pymysql
import os
import pandas as pd


from pymongo import MongoClient
client=MongoClient("mongodb+srv://Ever77x:Nico2014*@cluster0.nh47y.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db=client.db_companies
collection_companies = db.companies

In [22]:
client.list_database_names()

['Probando',
 'db_companies',
 'sakila',
 'sample_airbnb',
 'sample_analytics',
 'sample_geospatial',
 'sample_mflix',
 'sample_restaurants',
 'sample_supplies',
 'sample_training',
 'sample_weatherdata',
 'admin',
 'local']

# Answers
### 1. All the companies that it's name match 'Babelgum'. Retrieve only their `name` field.

In [47]:
answer1 = pd.DataFrame(collection_companies.find({"name": "Babelgum"}, {"name": 1, "_id": 0}))
answer1

       name
0  Babelgum

### 2. All the companies that have more than 5000 employees. Limit the search to 20 companies and sort them by **number of employees**.

In [41]:
Paso1 = collection_companies.find({"number_of_employees": {"$gt": 5000} })
Paso2 = Paso1.sort("number_of_employees", -1)
Paso3 = Paso2.limit(20)
Paso4 = pd.DataFrame(Paso3)
Paso4

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7d4bab8bd67529941a,Siemens,siemens,http://www.crunchbase.com/company/siemens,http://www.siemens.com,,,Siemens,hardware,405000,...,[],None,"[{'price_amount': 418000000, 'price_currency_c...","[{'description': '', 'address1': 'Wittelsbache...","[{'id': 35852, 'description': 'Siemens Receive...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<iframe width=""420"" height=""3...","[{'available_sizes': [[[150, 92], 'assets/imag...",[],[]
1,52cdef7c4bab8bd67529856a,IBM,ibm,http://www.crunchbase.com/company/ibm,http://www.ibm.com,,,IBM,software,388000,...,"[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Corporate Headquarters', 'ad...","[{'id': 10471, 'description': 'IBM Completes A...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 93], 'assets/imag...","[{'external_url': 'http://mashpedia.com/IBM', ...",[]
2,52cdef7d4bab8bd675299d33,Toyota,toyota,http://www.crunchbase.com/company/toyota,http://www.toyota-global.com,,,Toyota,enterprise,320000,...,"[{'funding_round': {'round_code': 'a', 'source...",None,[],"[{'description': 'HQ', 'address1': 'Toyota Mot...",[],None,"[{'embed_code': '<iframe width=""430"" height=""3...","[{'available_sizes': [[[150, 84], 'assets/imag...",[],[]
3,52cdef7c4bab8bd675297e89,PayPal,paypal,http://www.crunchbase.com/company/paypal,http://www.paypal.com,,,paypal,finance,300000,...,"[{'funding_round': {'round_code': 'c', 'source...","{'price_amount': 1500000000, 'price_currency_c...","[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '2145 E Hamil...","[{'id': 11916, 'description': 'Reserve Bank Of...",None,[],"[{'available_sizes': [[[150, 120], 'assets/ima...",[{'external_url': 'http://www.sociableblog.com...,[]
4,52cdef7e4bab8bd67529b0fe,Nippon Telegraph and Telephone Corporation,nippon-telegraph-and-telephone-corporation,http://www.crunchbase.com/company/nippon-teleg...,http://www.ntt.co.jp/index_e.html,,,,None,227000,...,"[{'funding_round': {'round_code': 'e', 'source...",None,[],"[{'description': 'NTT', 'address1': '3-1, Otem...",[],None,[],"[{'available_sizes': [[[150, 42], 'assets/imag...",[],[]
5,52cdef7d4bab8bd675298aa4,Samsung Electronics,samsung-electronics,http://www.crunchbase.com/company/samsung-elec...,http://www.samsung.com/us,http://www.samsungvillage.com/,,samsungtweets,hardware,221726,...,"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'HQ - South Korea', 'address1...","[{'id': 11908, 'description': 'Samsung Ships 3...",None,"[{'embed_code': '<iframe src=""http://blip.tv/p...","[{'available_sizes': [[[94, 150], 'assets/imag...",[{'external_url': 'http://mashpedia.com/Samsun...,[]
6,52cdef7d4bab8bd675298b99,Accenture,accenture,http://www.crunchbase.com/company/accenture,http://www.accenture.com,http://www.accenture.com/Global/Accenture_Blogs/,http://feeds.accenture.com/Accenture_High_Perf...,accenture,consulting,205000,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '1615 Murray ...","[{'id': 1824, 'description': 'Nokia and Accent...","{'valuation_amount': None, 'valuation_currency...",[],"[{'available_sizes': [[[150, 136], 'assets/ima...",[{'external_url': 'http://www.accenture.com/Gl...,[]
7,52cdef7e4bab8bd67529a657,Tata Consultancy Services,tata-consultancy-services,http://www.crunchbase.com/company/tata-consult...,http://www.tcs.com,,http://www.tcs.com/rss_feeds/Pages/feed.aspx?f=p,TCS_News,consulting,200300,...,[],None,[],"[{'description': 'World Headquarters', 'addres...",[],None,[],[],[],[]
8,52cdef7e4bab8bd67529aa51,Flextronics International,flextronics-international,http://www.crunchbase.com/company/flextronics-...,http://www.flextronics.com,http://www.flextronicsblog.com/,,flextronics,None,200000,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'US HQ', 'address1': '6201 Am...",[],None,[],"[{'available_sizes': [[[150, 107], 'assets/ima...",[],[]
9,52cdef7d4bab8bd675299156,Safeway,safeway,http://www.crunchbase.com/company/safeway,http://www.safeway.com,,,,other,186000,...,[],None,[],"[{'description': 'HQ', 'address1': '5918 Stone...",[],None,[],"[{'available_sizes': [[[150, 123], 'assets/ima...",[],[]
10,52cdef7c4bab8bd675297e6f,Sony,sony,http://www.crunchbase.com/company/sony,http://www.sony.com,http://blog.sony.com/,http://blog.sony.com/,Sony,hardware,180500,...,[],None,"[{'price_amount': 260000000, 'price_currency_c...","[{'description': 'HQ', 'address1': '16530 Via ...","[{'id': 18773, 'description': 'Sony Will Buy O...","{'valuation_amount': None, 'valuation_currency...",[],"[{'available_sizes': [[[150, 107], 'assets/ima...",[{'external_url': 'http://www.entechgadget.com...,[]
11,52cdef7c4bab8bd675298517,LG,lg,http://www.crunchbase.com/company/lg,http://www.lg.com,http://lgusblog.com/,,LGUS,hardware,177000,...,[{'funding_round': {'round_code': 'unattribute...,None,[],"[{'description': 'Headquarters', 'address1': '...",[],None,"[{'embed_code': '<iframe src=""http://blip.tv/p...",[],[],[]
12,52cdef7d4bab8bd675299d31,Ford,ford,http://www.crunchbase.com/company/ford,http://www.ford.com,,,FordService,automotive,171000,...,[],None,"[{'price_amount': 9000000, 'price_currency_cod...","[{'description': '', 'address1': 'One American...",[],"{'valuation_amount': None, 'valuation_currency...",[],[],[],[]
13,52cdef7d4bab8bd675298b28,Boeing,boeing,http://www.crunchbase.com/company/boeing,http://www.boeing.com,,,boeingairplanes,other,160000,...,[],None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Corporate Headquarters', 'ad...","[{'id': 44355, 'description': ' Boeing To Rep...",None,[],"[{'available_sizes': [[[150, 94], 'assets/imag...","[{'external_url': 'http://jobs-boeing.com/', '...",[]
14,52cdef7e4bab8bd67529bb5c,Digital Equipment Corporation,digital-equipment-corporation,http://www.crunchbase.com/company/digital-equi...,,,,,None,140000,...,[],None,[],"[{'description': 'HQ', 'address1': '', 'addres...","[{'id': 12279, 'description': 'Ken Olsen, co-f...",None,[],[],[],[]
15,52cdef7c4bab8bd675297fc2,Nokia,nokia,http://www.crunchbase.com/company/nokia,http://nokia.com,,,nokia,mobile,125000,...,"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': 96800000, 'price_currency_co...","[{'description': 'headquarter', 'address1': 'K...","[{'id': 9161, 'description': 'Nokia, AT&T Putt...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 131], 'assets/ima...",[{'external_url': 'http://en.wikipedia.org/wik...,[]
16,52cdef7d4bab8bd675299839,MItsubishi Electric,mitsubishi-electric,http://www.crunchbase.com/company/mitsubishi-e...,http://global.mitsubishielectric.com,,,,hardware,107000,...,[],None,[],"[{'description': 'HQ', 'address1': 'Tokyo Buil...",[],None,[],"[{'available_sizes': [[[150, 145], 'assets/ima...",[],[]
17,52cdef7d4bab8bd675299bc3,MItsubishi Electric,mitsubishi-electric,http://www.crunchbase.com/company/mitsubishi-e...,http://global.mitsubishielectric.com,,,,hardware,107000,...,[],None,[],"[{'description': 'HQ', 'address1': 'Tokyo Buil...",[],None,[],"[{'available_sizes': [[[150, 145], 'assets/ima...",[],[]
18,52cdef7c4bab8bd6752987ad,Comcast,comcast,http://www.crunchbase.com/company/comcast,http://comcast.com,,,XFINITYDeals,games_video,100000,...,"[{'funding_round': {'round_code': 'a', 'source...",None,"[{'price_amount': 150000000, 'price_currency_c...","[{'description': 'One Comcast Center', 'addres...","[{'id': 24946, 'description': 'Comcast buys Mi...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 94], 'assets/imag...",[],[]
19,52cdef7d4bab8bd675298d67,Bertelsmann,bertelsmann,http://www.crunchbase.com/company/bertelsmann,http://www.bertelsmann.com,,,None,other,100000,...,"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Corporate Headquarters', 'ad...","[{'id': 20443, 'description': 'A Step Forward?...",None,[],[],[],[]

### 3. All the companies founded between 2000 and 2005, both years included. Retrieve only the `name` and `founded_year` fileds.

In [52]:
answer3 = pd.DataFrame(collection_companies.find({"founded_year": {"$gt": 2000, "$lte": 2005} }, {"name":1, "founded_year":1, "_id":0}))
answer3

                         name  founded_year
0                    Wetpaint          2005
1                        Zoho          2005
2                        Digg          2004
3                    Facebook          2004
4                   Omnidrive          2005
...                       ...           ...
3208           Cameron Health          2001
3209  Celestial Semiconductor          2004
3210           Axon Solutions          2004
3211                  Intergy          2003
3212               AfterLogic          2002

[3213 rows x 2 columns]

### 4. All the companies that had a Valuation Amount of more than 100.000.000 and have been founded before 2010. Retrieve only the `name` and `ipo` fields.

In [60]:
answer3 = pd.DataFrame(collection_companies.find({'$and': [{"ipo.valuation_amount": {'$gt': 100000000}}, {'founded_year': {'$lt': 2010}}]}, {'name': 1, 'ipo': 1, '_id': 0}))
answer3

                    name                                                ipo
0               Facebook  {'valuation_amount': 104000000000, 'valuation_...
1                Twitter  {'valuation_amount': 18100000000, 'valuation_c...
2                   Yelp  {'valuation_amount': 1300000000, 'valuation_cu...
3               LinkedIn  {'valuation_amount': 9310000000, 'valuation_cu...
4                 Amazon  {'valuation_amount': 100000000000, 'valuation_...
5             Brightcove  {'valuation_amount': 290000000, 'valuation_cur...
6            KIT digital  {'valuation_amount': 235000000, 'valuation_cur...
7                Nielsen  {'valuation_amount': 1600000000, 'valuation_cu...
8              OpenTable  {'valuation_amount': 1050000000, 'valuation_cu...
9         ChannelAdvisor  {'valuation_amount': 287000000, 'valuation_cur...
10         Jive Software  {'valuation_amount': 1000000000, 'valuation_cu...
11                Zillow  {'valuation_amount': 2550000000, 'valuation_cu...
12                   Wix  {'valuation_amount': 750000000, 'valuation_cur...
13            Shutterfly  {'valuation_amount': 350000000, 'valuation_cur...
14           TripAdvisor  {'valuation_amount': 3273770000, 'valuation_cu...
15            Salesforce  {'valuation_amount': 110000000, 'valuation_cur...
16              HomeAway  {'valuation_amount': 3000000000, 'valuation_cu...
17            QuinStreet  {'valuation_amount': 140000000, 'valuation_cur...
18             Rackspace  {'valuation_amount': 5440000000, 'valuation_cu...
19          BMC Software  {'valuation_amount': 6000000000, 'valuation_cu...
20            Higher One  {'valuation_amount': 1060000000, 'valuation_cu...
21              Infoblox  {'valuation_amount': 824000000, 'valuation_cur...
22               Tencent  {'valuation_amount': 11000000000, 'valuation_c...
23               Marketo  {'valuation_amount': 465000000, 'valuation_cur...
24                 Baidu  {'valuation_amount': 4000000000, 'valuation_cu...
25               Geeknet  {'valuation_amount': 134000000, 'valuation_cur...
26               Opsware  {'valuation_amount': 450000000, 'valuation_cur...
27               Telenav  {'valuation_amount': 337000000, 'valuation_cur...
28        Rally Software  {'valuation_amount': 315000000, 'valuation_cur...
29   BrightSource Energy  {'valuation_amount': 1000000000, 'valuation_cu...
30                  Mixi  {'valuation_amount': 970000000, 'valuation_cur...
31              QlikTech  {'valuation_amount': 1000000000, 'valuation_cu...
32                 Chegg  {'valuation_amount': 1100000000, 'valuation_cu...
33                 Chegg  {'valuation_amount': 1100000000, 'valuation_cu...
34               Groupon  {'valuation_amount': 12800000000, 'valuation_c...
35            SolarWinds  {'valuation_amount': 803000000, 'valuation_cur...
36                  GREE  {'valuation_amount': 108960000000, 'valuation_...
37                 Tudou  {'valuation_amount': 174000000, 'valuation_cur...
38             DemandTec  {'valuation_amount': 245000000, 'valuation_cur...
39  Cornerstone OnDemand  {'valuation_amount': 900000000, 'valuation_cur...
40       Western Digital  {'valuation_amount': 9430000000, 'valuation_cu...
41      Millennial Media  {'valuation_amount': 973500000, 'valuation_cur...

### 5. All the companies that have less than 1000 employees and have been founded before 2005. Order them by the number of employees and limit the search to 10 companies.

In [74]:
Paso1 = collection_companies.find({'$and': [{"number_of_employees": {'$lt': 1000}}, {'founded_year': {'$lt': 2005}}]})
Paso2 = Paso1.sort("number_of_employees", -1)
Paso3 = Paso2.limit(10)
Paso4 = pd.DataFrame(Paso3)
Paso4

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7d4bab8bd675298933,Infinera Corporation,infinera,http://www.crunchbase.com/company/infinera,http://www.infinera.com,,,InfineraCorp,network_hosting,974,...,[],None,[],"[{'description': 'Headquarters', 'address1': '...","[{'id': 20267, 'description': 'Infinera PICs S...","{'valuation_amount': None, 'valuation_currency...",[],"[{'available_sizes': [[[150, 112], 'assets/ima...",[],[]
1,52cdef7e4bab8bd67529ac95,NorthPoint Communications Group,northpoint-communications-group,http://www.crunchbase.com/company/northpoint-c...,,,,,network_hosting,948,...,[],None,[],"[{'description': 'HQ', 'address1': '303 Second...",[],None,[],[],[],[]
2,52cdef7f4bab8bd67529be17,888 Holdings,888-holdings,http://www.crunchbase.com/company/888-holdings,http://www.888holdingsplc.com,,,,games_video,931,...,[],None,"[{'price_amount': 18000000, 'price_currency_co...",[],[],None,[],"[{'available_sizes': [[[143, 150], 'assets/ima...",[],[]
3,52cdef7c4bab8bd6752986a2,Forrester Research,forrester-research,http://www.crunchbase.com/company/forrester-re...,http://forrester.com,http://blogs.forrester.com/colony/,http://blogs.forrester.com/colony/index.rdf,,consulting,903,...,[],None,"[{'price_amount': 4750000, 'price_currency_cod...","[{'description': None, 'address1': '400 Techno...","[{'id': 36801, 'description': 'Forrester: $2.1...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 93], 'assets/imag...",[{'external_url': 'http://blogs.forrester.com/...,[]
4,52cdef7e4bab8bd67529af6d,SonicWALL,sonicwall,http://www.crunchbase.com/company/sonicwall,http://www.sonicwall.com,,,sonicwall,security,900,...,[],"{'price_amount': 717000000, 'price_currency_co...","[{'price_amount': 25000000, 'price_currency_co...","[{'description': 'HQ', 'address1': '2001 Logic...","[{'id': 15615, 'description': 'SonicWALL Revol...",None,"[{'embed_code': '<iframe width=""480"" height=""3...",[],[],[]
5,52cdef7e4bab8bd67529b21b,Webmetrics,webmetrics,http://www.crunchbase.com/company/webmetrics,http://www.webmetrics.com,http://blog.webmetrics.com,http://feeds.feedburner.com/webmetricsperforma...,Webmetrics,software,900,...,[],None,[],"[{'description': '', 'address1': '9444 Waples'...",[],None,[],"[{'available_sizes': [[[150, 125], 'assets/ima...",[],[]
6,52cdef7e4bab8bd67529b3bd,Cornerstone OnDemand,cornerstone-ondemand,http://www.crunchbase.com/company/cornerstone-...,http://www.cornerstoneondemand.com,http://www.cornerstoneondemand.com/blog,http://www.cornerstoneondemand.com/blog,cornerstoneinc,software,881,...,[],None,[],"[{'description': 'Headquarters', 'address1': '...","[{'id': 7141, 'description': 'Announced hire o...","{'valuation_amount': 900000000, 'valuation_cur...",[],[],[],[]
7,52cdef7c4bab8bd675297ff0,Mozilla,mozilla,http://www.crunchbase.com/company/mozilla,http://mozilla.org,http://blog.mozilla.org,http://blog.mozilla.org/feed/,firefox,web,800,...,[{'funding_round': {'round_code': 'unattribute...,None,[],"[{'description': '', 'address1': '650 Castro S...","[{'id': 153, 'description': 'UnqVjH srogpklot...",None,"[{'embed_code': '<div style=""width:320px;""><di...",[],[{'external_url': 'http://mashpedia.com/Mozill...,[]
8,52cdef7c4bab8bd67529857e,Buongiorno,buongiorno,http://www.crunchbase.com/company/buongiorno,http://www.buongiorno.com,,,AnnPRBuongiorno,mobile,800,...,[],None,"[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': 'Via Cosimo d...","[{'id': 23902, 'description': 'NTT DOCOMO, INC...","{'valuation_amount': None, 'valuation_currency...",[],[],[],[]
9,52cdef7c4bab8bd675297de0,Yelp,yelp,http://www.crunchbase.com/company/yelp,http://yelp.com,http://officialblog.yelp.com/,http://naturallylindy.com,Yelp,search,800,...,[],None,"[{'price_amount': 50000000, 'price_currency_co...","[{'description': '', 'address1': '706 Mission ...","[{'id': 5336, 'description': 'Yelp Launches in...","{'valuation_amount': 1300000000, 'valuation_cu...",[],"[{'available_sizes': [[[150, 75], 'assets/imag...",[{'external_url': 'http://en.wikipedia.org/wik...,[]

### 6. All the companies that don't include the `partners` field.

In [75]:
answer4 = pd.DataFrame(collection_companies.find({'partners': {'$exists': False}}))
answer4

Empty DataFrame
Columns: []
Index: []

### 7. All the companies that have a null type of value on the `category_code` field.

In [76]:
answer5 = pd.DataFrame(collection_companies.find({'category_code': {'$eq': None}}))
answer5

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd6752980f6,Collective,collective,http://www.crunchbase.com/company/collective,None,None,None,None,None,NaN,...,[],None,[],[],[],None,[],[],[],[]
1,52cdef7c4bab8bd675298225,Snimmer,snimmer,http://www.crunchbase.com/company/snimmer,None,None,None,None,None,NaN,...,[],None,[],[],[],None,[],[],[],[]
2,52cdef7c4bab8bd675298226,KoolIM,koolim,http://www.crunchbase.com/company/koolim,None,None,None,None,None,NaN,...,[],None,[],[],[],None,[],[],[],[]
3,52cdef7c4bab8bd675298261,Level9 Media,level9-media,http://www.crunchbase.com/company/level9-media,None,None,None,None,None,NaN,...,[],"{'price_amount': None, 'price_currency_code': ...",[],[],[],None,[],[],[],[]
4,52cdef7c4bab8bd675298262,VidKing,vidking,http://www.crunchbase.com/company/vidking,http://www.VidKing.com,,,None,None,NaN,...,[],"{'price_amount': 150000, 'price_currency_code'...",[],[],[],None,[],[],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2746,52cdef7f4bab8bd67529c6c8,Nellix,nellix,http://www.crunchbase.com/company/nellix,http://www.nellix.com,,,,None,NaN,...,[],"{'price_amount': None, 'price_currency_code': ...",[],"[{'description': '', 'address1': '2465-B Faber...",[],None,[],"[{'available_sizes': [[[150, 111], 'assets/ima...",[],[]
2747,52cdef7f4bab8bd67529c6de,Cantimer,cantimer,http://www.crunchbase.com/company/cantimer,http://www.cantimer.com,,,,None,NaN,...,[],None,[],"[{'description': '', 'address1': '3700 Haven C...",[],None,[],"[{'available_sizes': [[[150, 107], 'assets/ima...",[],[]
2748,52cdef7f4bab8bd67529c6e8,cruisecritic,cruisecritic,http://www.crunchbase.com/company/cruisecritic,None,None,None,None,None,NaN,...,[],None,[],[],[],None,[],[],[],[]
2749,52cdef7f4bab8bd67529c6e9,Coloroot,coloroot,http://www.crunchbase.com/company/coloroot,None,None,None,None,None,NaN,...,[],None,[],[],[],None,[],[],[],[]
2750,52cdef7f4bab8bd67529c6f4,Geekdive,geekdive,http://www.crunchbase.com/company/geekdive,None,None,None,None,None,NaN,...,[],None,[],[],[],None,[],[],[],[]

### 8. All the companies that have at least 100 employees but less than 1000. Retrieve only the `name` and `number of employees` fields.

In [77]:
answer5 = pd.DataFrame(collection_companies.find({'number_of_employees': {'$gte': 100, '$lt': 1000}}, {"_id":0, "name":1, "number_of_employees":1}))
answer5

                      name  number_of_employees
0                AdventNet                  600
1                  AddThis                  120
2                    OpenX                  305
3                 LifeLock                  644
4                    Jajah                  110
..                     ...                  ...
912  UOL (Universo Online)                  500
913               NextLabs                  100
914      OfficialVirtualDJ                  102
915          Willdan Group                  385
916                   QSGI                  164

[917 rows x 2 columns]

### 9. Order all the companies by their IPO price descendently.

In [79]:
Paso1 = collection_companies.find({'ipo': {'$not': {'$eq': None}}})
Paso2 = Paso1.sort('ipo.valuation_amount', -1)
Paso3 = pd.DataFrame(Paso2)
Paso3

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7e4bab8bd67529a8b4,GREE,gree,http://www.crunchbase.com/company/gree,http://www.gree-corp.com,,,gree_corp,games_video,700.0,...,"[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': 104000000, 'price_currency_c...","[{'description': 'Headquarters', 'address1': '...","[{'id': 1021, 'description': 'IPO', 'stoned_ye...","{'valuation_amount': 108960000000, 'valuation_...",[],"[{'available_sizes': [[[133, 150], 'assets/ima...",[],[]
1,52cdef7c4bab8bd675297d8e,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,...,"[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Headquarters', 'address1': '...","[{'id': 108, 'description': 'Facebook adds com...","{'valuation_amount': 104000000000, 'valuation_...",[],"[{'available_sizes': [[[150, 68], 'assets/imag...",[{'external_url': 'http://latimesblogs.latimes...,[]
2,52cdef7c4bab8bd675297e7a,Amazon,amazon,http://www.crunchbase.com/company/amazon,http://amazon.com,,,amazon,ecommerce,NaN,...,"[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': None, 'address1': '1200 12th ...","[{'id': 6931, 'description': 'How Many Kindle ...","{'valuation_amount': 100000000000, 'valuation_...","[{'embed_code': '<object width=""425"" height=""3...","[{'available_sizes': [[[150, 94], 'assets/imag...",[],[]
3,52cdef7c4bab8bd675297d94,Twitter,twitter,http://www.crunchbase.com/company/twitter,http://twitter.com,http://twitter.com/blog,http://feeds.feedburner.com/TwitterBlog,twitter,social,1300.0,...,[],None,"[{'price_amount': 15000000, 'price_currency_co...","[{'description': '', 'address1': '1355 Market ...","[{'id': 1, 'description': 'Survives iPhone 3G ...","{'valuation_amount': 18100000000, 'valuation_c...","[{'embed_code': '<iframe width=""430"" height=""2...","[{'available_sizes': [[[150, 74], 'assets/imag...",[{'external_url': 'http://sec.gov/cgi-bin/brow...,[]
4,52cdef7d4bab8bd675299d5d,Groupon,groupon,http://www.crunchbase.com/company/groupon,http://www.groupon.com,http://www.groupon.com/blog/,feed://feeds2.feedburner.com/grouponblog,groupon,web,10000.0,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'HQ', 'address1': '600 W. Chi...","[{'id': 4396, 'description': 'Groupon Makes A ...","{'valuation_amount': 12800000000, 'valuation_c...","[{'embed_code': '<script src=""http://www.buzzs...","[{'available_sizes': [[[150, 97], 'assets/imag...",[{'external_url': 'http://web20show.com/2009/1...,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,52cdef7f4bab8bd67529c5fe,InfoLogix,infologix,http://www.crunchbase.com/company/infologix,http://www.infologix.com,,,,enterprise,206.0,...,[],"{'price_amount': 61200000, 'price_currency_cod...","[{'price_amount': 2140000, 'price_currency_cod...","[{'description': '', 'address1': '101 East Cou...",[],"{'valuation_amount': None, 'valuation_currency...",[],"[{'available_sizes': [[[150, 81], 'assets/imag...",[],[]
386,52cdef7f4bab8bd67529c609,INX,inx,http://www.crunchbase.com/company/inx,http://www.inxi.com,,,Presidio,network_hosting,433.0,...,[],None,"[{'price_amount': 7350000, 'price_currency_cod...","[{'description': '', 'address1': '6401 South W...","[{'id': 1835, 'description': 'INX, Inc. announ...","{'valuation_amount': None, 'valuation_currency...",[],[],[],[]
387,52cdef7f4bab8bd67529c60b,Oxford Instruments,oxford-instruments,http://www.crunchbase.com/company/oxford-instr...,http://www.oxinst.com,,,oxinst,semiconductor,NaN,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': 8200000, 'price_currency_cod...","[{'description': '', 'address1': 'Tubney Woods...",[],"{'valuation_amount': None, 'valuation_currency...",[],[],[],[]
388,52cdef7f4bab8bd67529c61b,Zebra Technologies,zebra-technologies,http://www.crunchbase.com/company/zebra-techno...,http://www.zebra.com,http://black.creativesolutionsmall.com/index.p...,http://black.creativesolutionsmall.com/index.p...,ZebraTechnology,enterprise,3200.0,...,"[{'funding_round': {'round_code': 'd', 'source...",None,"[{'price_amount': 18000000, 'price_currency_co...","[{'description': '', 'address1': '475 Half Day...",[],"{'valuation_amount': None, 'valuation_currency...",[],[],[],[]
389,52cdef7f4bab8bd67529c637,Lenovo,lenovo,http://www.crunchbase.com/company/lenovo,http://www.lenovo.com,,,,hardware,NaN,...,"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': 200000000, 'price_currency_c...","[{'description': '', 'address1': '1009 Think P...","[{'id': 9196, 'description': 'LENOVO REACHES M...","{'valuation_amount': None, 'valuation_currency...",[],[],[{'external_url': 'http://startuptunes.com/201...,"[{'partner_name': 'CTQuan', 'homepage_url': 'h..."

### 10. Retrieve the 10 companies with more employees, order by the `number of employees`

In [84]:
Paso1 = collection_companies.find({})
Paso2 = Paso1.sort('number_of_employees', -1)
Paso3 = Paso2.limit(10)
Paso4 = pd.DataFrame(Paso3)
Paso4

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7d4bab8bd67529941a,Siemens,siemens,http://www.crunchbase.com/company/siemens,http://www.siemens.com,,,Siemens,hardware,405000,...,[],None,"[{'price_amount': 418000000, 'price_currency_c...","[{'description': '', 'address1': 'Wittelsbache...","[{'id': 35852, 'description': 'Siemens Receive...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<iframe width=""420"" height=""3...","[{'available_sizes': [[[150, 92], 'assets/imag...",[],[]
1,52cdef7c4bab8bd67529856a,IBM,ibm,http://www.crunchbase.com/company/ibm,http://www.ibm.com,,,IBM,software,388000,...,"[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Corporate Headquarters', 'ad...","[{'id': 10471, 'description': 'IBM Completes A...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 93], 'assets/imag...","[{'external_url': 'http://mashpedia.com/IBM', ...",[]
2,52cdef7d4bab8bd675299d33,Toyota,toyota,http://www.crunchbase.com/company/toyota,http://www.toyota-global.com,,,Toyota,enterprise,320000,...,"[{'funding_round': {'round_code': 'a', 'source...",None,[],"[{'description': 'HQ', 'address1': 'Toyota Mot...",[],None,"[{'embed_code': '<iframe width=""430"" height=""3...","[{'available_sizes': [[[150, 84], 'assets/imag...",[],[]
3,52cdef7c4bab8bd675297e89,PayPal,paypal,http://www.crunchbase.com/company/paypal,http://www.paypal.com,,,paypal,finance,300000,...,"[{'funding_round': {'round_code': 'c', 'source...","{'price_amount': 1500000000, 'price_currency_c...","[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '2145 E Hamil...","[{'id': 11916, 'description': 'Reserve Bank Of...",None,[],"[{'available_sizes': [[[150, 120], 'assets/ima...",[{'external_url': 'http://www.sociableblog.com...,[]
4,52cdef7e4bab8bd67529b0fe,Nippon Telegraph and Telephone Corporation,nippon-telegraph-and-telephone-corporation,http://www.crunchbase.com/company/nippon-teleg...,http://www.ntt.co.jp/index_e.html,,,,None,227000,...,"[{'funding_round': {'round_code': 'e', 'source...",None,[],"[{'description': 'NTT', 'address1': '3-1, Otem...",[],None,[],"[{'available_sizes': [[[150, 42], 'assets/imag...",[],[]
5,52cdef7d4bab8bd675298aa4,Samsung Electronics,samsung-electronics,http://www.crunchbase.com/company/samsung-elec...,http://www.samsung.com/us,http://www.samsungvillage.com/,,samsungtweets,hardware,221726,...,"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'HQ - South Korea', 'address1...","[{'id': 11908, 'description': 'Samsung Ships 3...",None,"[{'embed_code': '<iframe src=""http://blip.tv/p...","[{'available_sizes': [[[94, 150], 'assets/imag...",[{'external_url': 'http://mashpedia.com/Samsun...,[]
6,52cdef7d4bab8bd675298b99,Accenture,accenture,http://www.crunchbase.com/company/accenture,http://www.accenture.com,http://www.accenture.com/Global/Accenture_Blogs/,http://feeds.accenture.com/Accenture_High_Perf...,accenture,consulting,205000,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '1615 Murray ...","[{'id': 1824, 'description': 'Nokia and Accent...","{'valuation_amount': None, 'valuation_currency...",[],"[{'available_sizes': [[[150, 136], 'assets/ima...",[{'external_url': 'http://www.accenture.com/Gl...,[]
7,52cdef7e4bab8bd67529a657,Tata Consultancy Services,tata-consultancy-services,http://www.crunchbase.com/company/tata-consult...,http://www.tcs.com,,http://www.tcs.com/rss_feeds/Pages/feed.aspx?f=p,TCS_News,consulting,200300,...,[],None,[],"[{'description': 'World Headquarters', 'addres...",[],None,[],[],[],[]
8,52cdef7e4bab8bd67529aa51,Flextronics International,flextronics-international,http://www.crunchbase.com/company/flextronics-...,http://www.flextronics.com,http://www.flextronicsblog.com/,,flextronics,None,200000,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'US HQ', 'address1': '6201 Am...",[],None,[],"[{'available_sizes': [[[150, 107], 'assets/ima...",[],[]
9,52cdef7d4bab8bd675299156,Safeway,safeway,http://www.crunchbase.com/company/safeway,http://www.safeway.com,,,,other,186000,...,[],None,[],"[{'description': 'HQ', 'address1': '5918 Stone...",[],None,[],"[{'available_sizes': [[[150, 123], 'assets/ima...",[],[]

### 11. All the companies founded on the second semester of the year. Limit your search to 1000 companies.

In [86]:
Paso1 = collection_companies.find({'founded_month': {'$gte': 7}})
Paso2 = Paso1.limit(1000)
Paso3 = pd.DataFrame(Paso2)
Paso3

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,offices,milestones,video_embeds,screenshots,external_links,partners,deadpooled_month,deadpooled_day,deadpooled_url,ipo
0,52cdef7c4bab8bd675297d8a,Wetpaint,abc2,http://www.crunchbase.com/company/wetpaint,http://wetpaint-inc.com,http://digitalquarters.net/,http://digitalquarters.net/feed/,BachelrWetpaint,web,47.0,...,"[{'description': '', 'address1': '710 - 2nd Av...","[{'id': 5869, 'description': 'Wetpaint named i...",[],"[{'available_sizes': [[[150, 86], 'assets/imag...",[{'external_url': 'http://www.geekwire.com/201...,[],NaN,NaN,NaN,NaN
1,52cdef7c4bab8bd675297d8c,Zoho,abc4,http://www.crunchbase.com/company/zoho,http://zoho.com,http://blogs.zoho.com/,http://blogs.zoho.com/feed,zoho,software,1600.0,...,"[{'description': 'Headquarters', 'address1': '...","[{'id': 388, 'description': 'Zoho Reaches 2 Mi...","[{'embed_code': '<object width=""430"" height=""2...",[],[{'external_url': 'http://www.online-tech-tips...,[],NaN,NaN,NaN,NaN
2,52cdef7c4bab8bd675297d8d,Digg,digg,http://www.crunchbase.com/company/digg,http://www.digg.com,http://blog.digg.com/,http://blog.digg.com/?feed=rss2,digg,news,60.0,...,"[{'description': None, 'address1': '135 Missis...","[{'id': 9588, 'description': 'Another Digg Exe...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[117, 150], 'assets/ima...",[{'external_url': 'http://www.sociableblog.com...,[],NaN,NaN,None,None
3,52cdef7c4bab8bd675297d8f,Omnidrive,omnidrive,http://www.crunchbase.com/company/omnidrive,http://www.omnidrive.com,http://www.omnidrive.com/blog,http://feeds.feedburner.com/omnidrive,Nomadesk,network_hosting,NaN,...,"[{'description': '', 'address1': 'Suite 200', ...",[],[],[],[],[],9.0,15.0,,None
4,52cdef7c4bab8bd675297d9b,eBay,ebay,http://www.crunchbase.com/company/ebay,http://ebay.com,,,eBay,web,15000.0,...,"[{'description': 'Headquarters', 'address1': '...","[{'id': 7107, 'description': 'eBay Q2 Revenue ...","[{'embed_code': '<iframe width=""370"" height=""3...","[{'available_sizes': [[[150, 71], 'assets/imag...",[],[],NaN,NaN,None,"{'valuation_amount': None, 'valuation_currency..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,52cdef7d4bab8bd675299145,LingusTV,lingustv,http://www.crunchbase.com/company/lingustv,http://www.lingus.tv,http://www.lingus.tv/blog,http://feeds.feedburner.com/learn-spanish?form...,lingustv,games_video,15.0,...,"[{'description': 'World Headquarters', 'addres...",[],[],"[{'available_sizes': [[[150, 150], 'assets/ima...",[{'external_url': 'http://www.lingus.tv/videos...,[],NaN,NaN,None,None
996,52cdef7d4bab8bd675299148,AccountMaven,accountmaven,http://www.crunchbase.com/company/accountmaven,http://www.accountmaven.com,http://accountmaven.wordpress.com,http://accountmaven.wordpress.com/feed/,None,network_hosting,5.0,...,"[{'description': 'San Francisco', 'address1': ...",[],[],[],[],[],NaN,NaN,None,None
997,52cdef7d4bab8bd67529914f,Chapatiz,chapatiz,http://www.crunchbase.com/company/chapatiz,http://chapatiz.com,http://www.chapacorp.com,,chapatiz,games_video,7.0,...,"[{'description': '', 'address1': 'PÃ©piniÃ¨re ...",[],[],"[{'available_sizes': [[[150, 134], 'assets/ima...",[],[],NaN,NaN,None,None
998,52cdef7d4bab8bd67529915e,YOOWALK,yoowalk,http://www.crunchbase.com/company/yoowalk,http://www.yoowalk.com,http://blog.yoowalk.com,,None,games_video,10.0,...,"[{'description': '', 'address1': '28 rue FrÃ©m...",[],[],[],[],[],NaN,NaN,None,None
999,52cdef7d4bab8bd675299170,Data Domain,data-domain,http://www.crunchbase.com/company/data-domain,http://www.emc.com/datadomain,,,,enterprise,NaN,...,"[{'description': 'EMC Backup Division', 'addre...","[{'id': 1772, 'description': 'Data Domain was ...",[],"[{'available_sizes': [[[150, 97], 'assets/imag...",[],[],NaN,NaN,None,None

### 12. All the companies that have been 'deadpooled' after the third year.

In [87]:
answer6 = pd.DataFrame(collection_companies.find({'$expr': {'$gt': ['$deadpooled_year', {'$add': ['$founded_year',3]}]}}))
answer6

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd675297da0,Babelgum,babelgum,http://www.crunchbase.com/company/babelgum,http://babelgum.com,http://babelgum.com/blog,http://feeds.feedburner.com/Babelgum,Babelgum,games_video,NaN,...,[],None,[],"[{'description': '', 'address1': '', 'address2...",[],None,[],[],[],[]
1,52cdef7c4bab8bd675297dae,Thoof,thoof,http://www.crunchbase.com/company/thoof,http://thoof.com,,None,None,web,NaN,...,[],None,[],"[{'description': None, 'address1': None, 'addr...",[],None,[],[],[{'external_url': 'http://www.duraslide.com.sg...,[]
2,52cdef7c4bab8bd675297db3,Mercora,mercora,http://www.crunchbase.com/company/mercora,http://mercora.com,http://blog.social.fm/,http://blog.social.fm/?feed=rss2,,web,NaN,...,[],None,[],"[{'description': None, 'address1': '440 N. Wol...",[],None,[],[],[],[]
3,52cdef7c4bab8bd675297db6,Wesabe,wesabe,http://www.crunchbase.com/company/wesabe,http://wesabe.com,http://blog.wesabe.com/,http://blog.wesabe.com/feed/,jasonlong,web,NaN,...,[],None,[],"[{'description': None, 'address1': '400 Montgo...",[],None,"[{'embed_code': '<script src=""http://flash.rev...",[],[],[]
4,52cdef7c4bab8bd675297dbe,Stickam,stickam,http://www.crunchbase.com/company/stickam,http://www.stickam.com,http://webmaster.stickam.com,http://blog.stickam.com/index.php/feed/,Stickam,games_video,35.0,...,[],None,[],"[{'description': '', 'address1': '1975 pads rd...",[],None,[],[],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650,52cdef7f4bab8bd67529c579,TrueSpan,truespan,http://www.crunchbase.com/company/truespan,http://www.truespaninc.com,,,,mobile,NaN,...,[],None,[],"[{'description': 'US Office', 'address1': '378...",[],None,[],[],[],[]
651,52cdef7f4bab8bd67529c590,Eyetronics,eyetronics,http://www.crunchbase.com/company/eyetronics,http://www.eyetronics.com,,,,games_video,NaN,...,[],None,[],"[{'description': '', 'address1': 'Kapeldreef 6...",[],None,[],"[{'available_sizes': [[[150, 89], 'assets/imag...",[],[]
652,52cdef7f4bab8bd67529c5aa,Nethra Imaging,nethra-imaging,http://www.crunchbase.com/company/nethra-imaging,http://nethra-imaging.com/index.php,,,,semiconductor,NaN,...,[],None,"[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '2855 Bowers ...",[],None,[],"[{'available_sizes': [[[150, 135], 'assets/ima...",[],[]
653,52cdef7f4bab8bd67529c68b,Prolify,prolify,http://www.crunchbase.com/company/prolify,http://www.prolify.com,,,,None,NaN,...,[],None,[],"[{'description': 'HQ', 'address1': '7 Giborey ...",[],None,[],"[{'available_sizes': [[[150, 100], 'assets/ima...",[],[]
654,52cdef7f4bab8bd67529c6ec,Embedster,embedster,http://www.crunchbase.com/company/embedster,http://www.embedster.com,,,embedster,advertising,NaN,...,[],None,[],[],[],None,[],[],[],[]

### 13. All the companies founded before 2000 that have and acquisition amount of more than 10.000.000

In [88]:
answer7 = pd.DataFrame(collection_companies.find({'$and': [{'founded_year': {'$lt': 2000}}, {"acquisition.price_amount": {'$gt': 10000000}}]}))
answer7

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7c4bab8bd675297d90,Postini,postini,http://www.crunchbase.com/company/postini,http://postini.com,,,None,web,NaN,...,[],"{'price_amount': 625000000, 'price_currency_co...",[],"[{'description': None, 'address1': '959 Skyway...",[],None,[],[],[],[]
1,52cdef7c4bab8bd675297deb,SideStep,sidestep,http://www.crunchbase.com/company/sidestep,http://www.sidestep.com,None,None,None,web,75.0,...,[],"{'price_amount': 180000000, 'price_currency_co...",[],"[{'description': None, 'address1': '2980 Bower...",[],None,[],[],[],[]
2,52cdef7c4bab8bd675297e2c,Recipezaar,recipezaar,http://www.crunchbase.com/company/recipezaar,http://www.recipezaar.com,http://www.recipezaar.com/sitenews/,None,None,web,5.0,...,[],"{'price_amount': 25000000, 'price_currency_cod...",[],"[{'description': None, 'address1': 'P.O. Box 1...",[],None,[],[],[],[]
3,52cdef7c4bab8bd675297e89,PayPal,paypal,http://www.crunchbase.com/company/paypal,http://www.paypal.com,,,paypal,finance,300000.0,...,"[{'funding_round': {'round_code': 'c', 'source...","{'price_amount': 1500000000, 'price_currency_c...","[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '2145 E Hamil...","[{'id': 11916, 'description': 'Reserve Bank Of...",None,[],"[{'available_sizes': [[[150, 120], 'assets/ima...",[{'external_url': 'http://www.sociableblog.com...,[]
4,52cdef7c4bab8bd675297e97,Snapfish,snapfish,http://www.crunchbase.com/company/snapfish,http://snapfish.com,http://snapfishblog.in/,,snapfishbyhp,network_hosting,NaN,...,[],"{'price_amount': 300000000, 'price_currency_co...","[{'price_amount': None, 'price_currency_code':...","[{'description': None, 'address1': '303 Second...",[],None,[],[],[{'external_url': 'http://www.upickreviews.com...,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,52cdef7f4bab8bd67529c6a2,Savvion,savvion,http://www.crunchbase.com/company/savvion,http://www.savvion.com,,,,software,160.0,...,[],"{'price_amount': 49000000, 'price_currency_cod...",[],"[{'description': 'Corporate Headquarters', 'ad...",[],None,[],"[{'available_sizes': [[[150, 82], 'assets/imag...",[{'external_url': 'http://www.savvion.com/pres...,[]
201,52cdef7f4bab8bd67529c6ac,Inventa Technologies,inventa-technologies,http://www.crunchbase.com/company/inventa-tech...,http://www.inventa.com,,,,software,207.0,...,[],"{'price_amount': 30000000, 'price_currency_cod...",[],"[{'description': '', 'address1': '2040 Briggs ...",[],None,[],[],[],[]
202,52cdef7f4bab8bd67529c6bb,Universal Microwave,universal-microwave,http://www.crunchbase.com/company/universal-mi...,http://www.vco1.com,,,,mobile,NaN,...,[],"{'price_amount': 23200000, 'price_currency_cod...",[],"[{'description': '', 'address1': '6036 Nature ...",[],None,[],[],[],[]
203,52cdef7f4bab8bd67529c6c3,Advanced Control Components,advanced-control-components,http://www.crunchbase.com/company/advanced-con...,,,,,None,NaN,...,[],"{'price_amount': 18780000, 'price_currency_cod...",[],"[{'description': '', 'address1': '611 Industri...",[],None,[],[],[],[]
204,52cdef7f4bab8bd67529c6f2,Contemporary Computer Services,contemporary-computer-services,http://www.crunchbase.com/company/contemporary...,http://www.ccsinet.com,,,,software,NaN,...,[],"{'price_amount': 15040000, 'price_currency_cod...",[],"[{'description': '', 'address1': '200 Knickerb...",[],None,[],[],[],[]

### 14. All the companies that have been acquired after 2015, order by the acquisition amount, and retrieve only their `name` and `acquisiton` field.

In [89]:
answer8 = pd.DataFrame(collection_companies.find({'acquisition.acquired_year': {'$gt': 2015}}, {'name': 1, 'acquisition': 1, "_id": 0}).sort('acquisition.price_amount', -1))
answer8

Empty DataFrame
Columns: []
Index: []

### 15. Order the companies by their `founded year`, retrieving only their `name` and `founded year`.

### 16. All the companies that have been founded on the first seven days of the month, including the seventh. Sort them by their `aquisition price` descendently. Limit the search to 10 documents.

### 17. All the companies on the 'web' `category` that have more than 4000 employees. Sort them by the amount of employees in ascendant order.

### 18. All the companies which their acquisition amount is more than 10.000.000, and currency are 'EUR'.

### 19. All the companies that have been acquired on the first trimester of the year. Limit the search to 10 companies, and retrieve only their `name` and `acquisition` fields.

### 20. All the companies that have been founded between 2000 and 2010, but have not been acquired before 2011.