![Ironhack Logo](https://i.imgur.com/1QgrNNw.png)

In [109]:
from pymongo import MongoClient,DESCENDING
client=MongoClient('mongodb+srv://zk97:Zzkk9977-@cluster0-edyek.gcp.mongodb.net/db_companies?retryWrites=true&w=majority')
db=client.db_companies

# Answers
### 1. All the companies that it's name match 'Babelgum'. Retrieve only their `name` field.

In [92]:
for i,x in enumerate(db.companies.find({'name':'Babelgum'}, {'name':1,'_id':0})):
    if i<50:
        print(x,'\n')

{'name': 'Babelgum'}

### 2. All the companies that have more than 5000 employees. Limit the search to 20 companies and sort them by **number of employees**.

In [93]:
for i,x in enumerate(db.companies.find(filter={'number_of_employees':{'$gt':5000}},
                                       sort=[('number_of_employees',-1)],limit=(20),
                                       projection={'name':1,'_id':0,'number_of_employees':1})):
    if i<50:
        print(x,'\n')

{'name': 'Siemens', 'number_of_employees': 405000}

{'name': 'IBM', 'number_of_employees': 388000}

{'name': 'Toyota', 'number_of_employees': 320000}

{'name': 'PayPal', 'number_of_employees': 300000}

{'name': 'Nippon Telegraph and Telephone Corporation', 'number_of_employees': 227000}

{'name': 'Samsung Electronics', 'number_of_employees': 221726}

{'name': 'Accenture', 'number_of_employees': 205000}

{'name': 'Tata Consultancy Services', 'number_of_employees': 200300}

{'name': 'Flextronics International', 'number_of_employees': 200000}

{'name': 'Safeway', 'number_of_employees': 186000}

{'name': 'Sony', 'number_of_employees': 180500}

{'name': 'LG', 'number_of_employees': 177000}

{'name': 'Ford', 'number_of_employees': 171000}

{'name': 'Boeing', 'number_of_employees': 160000}

{'name': 'Digital Equipment Corporation', 'number_of_employees': 140000}

{'name': 'Nokia', 'number_of_employees': 125000}

{'name': 'MItsubishi Electric', 'number_of_employees': 107000}

{'name': 'MItsubishi Electric', 'number_of_employees': 107000}

{'name': 'Comcast', 'number_of_employees': 100000}

{'name': 'Bertelsmann', 'number_of_employees': 100000}

### 3. All the companies founded between 2000 and 2005, both years included. Retrieve only the `name` and `founded_year` fileds.

In [94]:
for i,x in enumerate(db.companies.find(filter={'$and':[{'founded_year':{'$gte':2000}},
                                                       {'founded_year':{'$lte':2005}}]},
                                       sort=[('founded_year',-1)],
                                       projection={'name':1,'_id':0,'founded_year':1})):
    if i<50:
        print(x,'\n')

{'name': 'Wetpaint', 'founded_year': 2005}

{'name': 'Zoho', 'founded_year': 2005}

{'name': 'Omnidrive', 'founded_year': 2005}

{'name': 'Helio', 'founded_year': 2005}

{'name': 'Jingle Networks', 'founded_year': 2005}

{'name': 'LifeLock', 'founded_year': 2005}

{'name': 'Wesabe', 'founded_year': 2005}

{'name': 'Jangl SMS', 'founded_year': 2005}

{'name': 'Jajah', 'founded_year': 2005}

{'name': 'YouTube', 'founded_year': 2005}

{'name': 'Revision3', 'founded_year': 2005}

{'name': 'iSkoot', 'founded_year': 2005}

{'name': 'ClipBlast!', 'founded_year': 2005}

{'name': 'Zlio', 'founded_year': 2005}

{'name': 'Dailymotion', 'founded_year': 2005}

{'name': 'RockYou', 'founded_year': 2005}

{'name': 'Instructables', 'founded_year': 2005}

{'name': 'Netvibes', 'founded_year': 2005}

{'name': 'Swivel', 'founded_year': 2005}

{'name': 'Slide', 'founded_year': 2005}

{'name': 'Bebo', 'founded_year': 2005}

{'name': 'TripHub', 'founded_year': 2005}

{'name': 'PBworks', 'founded_year': 2005}

{'name': 'Meebo', 'founded_year': 2005}

{'name': 'Newsvine', 'founded_year': 2005}

{'name': 'Jamendo', 'founded_year': 2005}

{'name': 'Box', 'founded_year': 2005}

{'name': 'Conduit', 'founded_year': 2005}

{'name': 'Kaboodle', 'founded_year': 2005}

{'name': 'Zvents', 'founded_year': 2005}

{'name': 'MotionDSP', 'founded_year': 2005}

{'name': 'oDesk', 'founded_year': 2005}

{'name': 'Bazaarvoice', 'founded_year': 2005}

{'name': 'barablu', 'founded_year': 2005}

{'name': 'Clipperz', 'founded_year': 2005}

{'name': 'ScanScout', 'founded_year': 2005}

{'name': 'Jaxtr', 'founded_year': 2005}

{'name': 'ONEsite', 'founded_year': 2005}

{'name': 'GoLightly', 'founded_year': 2005}

{'name': 'Kiptronic', 'founded_year': 2005}

{'name': 'Zenfolio', 'founded_year': 2005}

{'name': 'Vuze', 'founded_year': 2005}

{'name': 'PodTech', 'founded_year': 2005}

{'name': 'NowPublic', 'founded_year': 2005}

{'name': 'Reddit', 'founded_year': 2005}

{'name': 'BuddyTV', 'founded_year': 2005}

{'name': 'TextPayMe', 'founded_year': 2005}

{'name': 'obopay', 'founded_year': 2005}

{'name': 'BillMonk', 'founded_year': 2005}

{'name': 'PermissionTV', 'founded_year': 2005}

### 4. All the companies that had a Valuation Amount of more than 100.000.000 and have been founded before 2010. Retrieve only the `name` and `ipo` fields.

In [95]:
for i,x in enumerate(db.companies.find(filter={'$and':[{'ipo.valuation_amount':{'$gt':100000000}},
                                                       {'founded_year':{'$lt':2010}}]},
                                       sort=[('ipo.valuation_amount',-1)],
                                       projection={'name':1,'_id':0,'ipo':1})):
    if i<50:
        print(x,'\n')

{'name': 'GREE', 'ipo': {'valuation_amount': 108960000000, 'valuation_currency_code': 'JPY', 'pub_year': 2008, 'pub_month': 12, 'pub_day': 17, 'stock_symbol': '3632'}}

{'name': 'Facebook', 'ipo': {'valuation_amount': 104000000000, 'valuation_currency_code': 'USD', 'pub_year': 2012, 'pub_month': 5, 'pub_day': 18, 'stock_symbol': 'NASDAQ:FB'}}

{'name': 'Amazon', 'ipo': {'valuation_amount': 100000000000, 'valuation_currency_code': 'USD', 'pub_year': 1997, 'pub_month': 5, 'pub_day': None, 'stock_symbol': 'NASDAQ:AMZN'}}

{'name': 'Twitter', 'ipo': {'valuation_amount': 18100000000, 'valuation_currency_code': 'USD', 'pub_year': 2013, 'pub_month': 11, 'pub_day': 7, 'stock_symbol': 'NYSE:TWTR'}}

{'name': 'Groupon', 'ipo': {'valuation_amount': 12800000000, 'valuation_currency_code': 'USD', 'pub_year': 2011, 'pub_month': 11, 'pub_day': 7, 'stock_symbol': 'NASDAQ:GRPN'}}

{'name': 'Tencent', 'ipo': {'valuation_amount': 11000000000, 'valuation_currency_code': 'USD', 'pub_year': 2004, 'pub_month': 6, 'pub_day': 16, 'stock_symbol': 'HK:0700'}}

{'name': 'Western Digital', 'ipo': {'valuation_amount': 9430000000, 'valuation_currency_code': 'USD', 'pub_year': None, 'pub_month': None, 'pub_day': None, 'stock_symbol': 'NYSE:WDC'}}

{'name': 'LinkedIn', 'ipo': {'valuation_amount': 9310000000, 'valuation_currency_code': 'USD', 'pub_year': 2011, 'pub_month': 7, 'pub_day': 20, 'stock_symbol': 'NYSE:LNKD'}}

{'name': 'BMC Software', 'ipo': {'valuation_amount': 6000000000, 'valuation_currency_code': 'USD', 'pub_year': 1988, 'pub_month': 8, 'pub_day': 12, 'stock_symbol': 'NASDAQ:BMC'}}

{'name': 'Rackspace', 'ipo': {'valuation_amount': 5440000000, 'valuation_currency_code': 'USD', 'pub_year': 2011, 'pub_month': 11, 'pub_day': 7, 'stock_symbol': 'RAX'}}

{'name': 'Baidu', 'ipo': {'valuation_amount': 4000000000, 'valuation_currency_code': 'USD', 'pub_year': 2005, 'pub_month': 8, 'pub_day': 5, 'stock_symbol': 'NASDAQ:BIDU'}}

{'name': 'TripAdvisor', 'ipo': {'valuation_amount': 3273770000, 'valuation_currency_code': 'USD', 'pub_year': 2011, 'pub_month': 12, 'pub_day': 21, 'stock_symbol': 'TRIP'}}

{'name': 'HomeAway', 'ipo': {'valuation_amount': 3000000000, 'valuation_currency_code': 'USD', 'pub_year': 2011, 'pub_month': 6, 'pub_day': 29, 'stock_symbol': 'NASDAQ:AWAY'}}

{'name': 'Zillow', 'ipo': {'valuation_amount': 2550000000, 'valuation_currency_code': 'USD', 'pub_year': 2011, 'pub_month': 7, 'pub_day': 19, 'stock_symbol': 'NASDAQ:Z'}}

{'name': 'Nielsen', 'ipo': {'valuation_amount': 1600000000, 'valuation_currency_code': 'USD', 'pub_year': 2011, 'pub_month': 1, 'pub_day': 26, 'stock_symbol': 'NYSE:NLSN'}}

{'name': 'Yelp', 'ipo': {'valuation_amount': 1300000000, 'valuation_currency_code': 'USD', 'pub_year': 2012, 'pub_month': 3, 'pub_day': 2, 'stock_symbol': 'NYSE:YELP'}}

{'name': 'Chegg', 'ipo': {'valuation_amount': 1100000000, 'valuation_currency_code': 'USD', 'pub_year': 2013, 'pub_month': 11, 'pub_day': 14, 'stock_symbol': 'NYSE:CHGG'}}

{'name': 'Chegg', 'ipo': {'valuation_amount': 1100000000, 'valuation_currency_code': 'USD', 'pub_year': 2013, 'pub_month': 11, 'pub_day': 14, 'stock_symbol': 'NYSE:CHGG'}}

{'name': 'Higher One', 'ipo': {'valuation_amount': 1060000000, 'valuation_currency_code': 'USD', 'pub_year': None, 'pub_month': None, 'pub_day': None, 'stock_symbol': 'NYSE:ONE'}}

{'name': 'OpenTable', 'ipo': {'valuation_amount': 1050000000, 'valuation_currency_code': 'USD', 'pub_year': 2009, 'pub_month': 5, 'pub_day': 21, 'stock_symbol': 'NASDAQ:OPEN'}}

{'name': 'Jive Software', 'ipo': {'valuation_amount': 1000000000, 'valuation_currency_code': 'USD', 'pub_year': 2012, 'pub_month': 2, 'pub_day': 3, 'stock_symbol': 'NASDAQ:JIVE'}}

{'name': 'BrightSource Energy', 'ipo': {'valuation_amount': 1000000000, 'valuation_currency_code': 'USD', 'pub_year': 2011, 'pub_month': 4, 'pub_day': 22, 'stock_symbol': 'NASDAQ:BRSE'}}

{'name': 'QlikTech', 'ipo': {'valuation_amount': 1000000000, 'valuation_currency_code': 'USD', 'pub_year': 2010, 'pub_month': 7, 'pub_day': 16, 'stock_symbol': 'QLIK'}}

{'name': 'Millennial Media', 'ipo': {'valuation_amount': 973500000, 'valuation_currency_code': 'USD', 'pub_year': 2012, 'pub_month': 3, 'pub_day': 28, 'stock_symbol': 'NYSE:MM'}}

{'name': 'Mixi', 'ipo': {'valuation_amount': 970000000, 'valuation_currency_code': 'USD', 'pub_year': 2006, 'pub_month': 9, 'pub_day': 14, 'stock_symbol': 'JP:2121'}}

{'name': 'Cornerstone OnDemand', 'ipo': {'valuation_amount': 900000000, 'valuation_currency_code': 'USD', 'pub_year': 2011, 'pub_month': 7, 'pub_day': 5, 'stock_symbol': 'CSOD'}}

{'name': 'Infoblox', 'ipo': {'valuation_amount': 824000000, 'valuation_currency_code': 'USD', 'pub_year': 2012, 'pub_month': 4, 'pub_day': 20, 'stock_symbol': 'NYSE:BLOX'}}

{'name': 'SolarWinds', 'ipo': {'valuation_amount': 803000000, 'valuation_currency_code': 'USD', 'pub_year': 2009, 'pub_month': 5, 'pub_day': 20, 'stock_symbol': 'SWI'}}

{'name': 'Wix', 'ipo': {'valuation_amount': 750000000, 'valuation_currency_code': 'USD', 'pub_year': 2013, 'pub_month': 11, 'pub_day': 6, 'stock_symbol': 'NASDAQ:WIX'}}

{'name': 'Marketo', 'ipo': {'valuation_amount': 465000000, 'valuation_currency_code': 'USD', 'pub_year': 2013, 'pub_month': 4, 'pub_day': 2, 'stock_symbol': 'NASDAQ:MKTO'}}

{'name': 'Opsware', 'ipo': {'valuation_amount': 450000000, 'valuation_currency_code': 'USD', 'pub_year': 2001, 'pub_month': 3, 'pub_day': 9, 'stock_symbol': 'NASDAQ:LDCL'}}

{'name': 'Shutterfly', 'ipo': {'valuation_amount': 350000000, 'valuation_currency_code': 'USD', 'pub_year': 2006, 'pub_month': 9, 'pub_day': 29, 'stock_symbol': 'SFLY'}}

{'name': 'Telenav', 'ipo': {'valuation_amount': 337000000, 'valuation_currency_code': 'USD', 'pub_year': 2010, 'pub_month': 5, 'pub_day': 13, 'stock_symbol': 'TNAV'}}

{'name': 'Rally Software', 'ipo': {'valuation_amount': 315000000, 'valuation_currency_code': 'USD', 'pub_year': 2013, 'pub_month': 4, 'pub_day': 12, 'stock_symbol': 'RALY'}}

{'name': 'Brightcove', 'ipo': {'valuation_amount': 290000000, 'valuation_currency_code': 'USD', 'pub_year': 2012, 'pub_month': 2, 'pub_day': 17, 'stock_symbol': 'NASDAQ:BCOV'}}

{'name': 'ChannelAdvisor', 'ipo': {'valuation_amount': 287000000, 'valuation_currency_code': 'USD', 'pub_year': 2013, 'pub_month': 5, 'pub_day': 23, 'stock_symbol': 'NYSE:ECOM'}}

{'name': 'DemandTec', 'ipo': {'valuation_amount': 245000000, 'valuation_currency_code': 'USD', 'pub_year': 2011, 'pub_month': 2, 'pub_day': 14, 'stock_symbol': 'NASDAQ:DMAN'}}

{'name': 'KIT digital', 'ipo': {'valuation_amount': 235000000, 'valuation_currency_code': 'USD', 'pub_year': 2010, 'pub_month': 7, 'pub_day': 27, 'stock_symbol': 'KITD'}}

{'name': 'Tudou', 'ipo': {'valuation_amount': 174000000, 'valuation_currency_code': 'USD', 'pub_year': None, 'pub_month': None, 'pub_day': None, 'stock_symbol': 'NASDAQ:TUDO'}}

{'name': 'QuinStreet', 'ipo': {'valuation_amount': 140000000, 'valuation_currency_code': 'USD', 'pub_year': 2010, 'pub_month': 1, 'pub_day': 11, 'stock_symbol': 'NASDAQ:QNST'}}

{'name': 'Geeknet', 'ipo': {'valuation_amount': 134000000, 'valuation_currency_code': 'USD', 'pub_year': 2010, 'pub_month': 11, 'pub_day': 2, 'stock_symbol': 'GKNT'}}

{'name': 'Salesforce', 'ipo': {'valuation_amount': 110000000, 'valuation_currency_code': 'USD', 'pub_year': 2004, 'pub_month': 7, 'pub_day': 2, 'stock_symbol': 'NYSE:CRM'}}

### 5. All the companies that have less than 1000 employees and have been founded before 2005. Order them by the number of employees and limit the search to 10 companies.

In [96]:
for i,x in enumerate(db.companies.find(filter={'$and':[{'number_of_employees':{'$lt':1000}},
                                                       {'founded_year':{'$lt':2005}}]},
                                       sort=[('number_of_employees',-1)],limit=(10),
                                       projection={'name':1,'_id':0,'founded_year':1,'number_of_employees':1})):
    if i<50:
        print(x,'\n')

{'name': 'Infinera Corporation', 'number_of_employees': 974, 'founded_year': 2000}

{'name': 'NorthPoint Communications Group', 'number_of_employees': 948, 'founded_year': 1997}

{'name': '888 Holdings', 'number_of_employees': 931, 'founded_year': 1997}

{'name': 'Forrester Research', 'number_of_employees': 903, 'founded_year': 1983}

{'name': 'SonicWALL', 'number_of_employees': 900, 'founded_year': 1991}

{'name': 'Webmetrics', 'number_of_employees': 900, 'founded_year': 1999}

{'name': 'Cornerstone OnDemand', 'number_of_employees': 881, 'founded_year': 1999}

{'name': 'Yelp', 'number_of_employees': 800, 'founded_year': 2004}

{'name': 'MySpace', 'number_of_employees': 800, 'founded_year': 2003}

{'name': 'ZoomInfo', 'number_of_employees': 800, 'founded_year': 2000}

### 6. All the companies that don't include the `partners` field.

In [47]:
for i,x in enumerate(db.companies.find({'partners':{'$exists':False}})):
    if i<50:
        print(x,'\n')

### 7. All the companies that have a null type of value on the `category_code` field.

In [97]:
for i,x in enumerate(db.companies.find(filter={'category_code':None},
                                       projection={'name':1,'_id':0,'category_code':1})):
    if i<50:
        print(x,'\n')

{'name': 'Collective', 'category_code': None}

{'name': 'Snimmer', 'category_code': None}

{'name': 'KoolIM', 'category_code': None}

{'name': 'Level9 Media', 'category_code': None}

{'name': 'VidKing', 'category_code': None}

{'name': 'Drigg', 'category_code': None}

{'name': 'SpaceTime', 'category_code': None}

{'name': 'Touch Clarity', 'category_code': None}

{'name': 'MMDAYS', 'category_code': None}

{'name': 'Inside Group', 'category_code': None}

{'name': 'Repeater Store', 'category_code': None}

{'name': 'Tapesh', 'category_code': None}

{'name': 'iPersians', 'category_code': None}

{'name': 'NewPersia', 'category_code': None}

{'name': 'Pyra Labs', 'category_code': None}

{'name': 'Feedmap', 'category_code': None}

{'name': 'NuvoMedia', 'category_code': None}

{'name': 'Intwine', 'category_code': None}

{'name': 'The Weinstein Company', 'category_code': None}

{'name': 'ExecuNet', 'category_code': None}

{'name': 'A1Vacations', 'category_code': None}

{'name': 'TripHomes', 'category_code': None}

{'name': 'Picturehouse', 'category_code': None}

{'name': 'Covalent Technologies', 'category_code': None}

{'name': 'Epic Trip', 'category_code': None}

{'name': 'Telepost', 'category_code': None}

{'name': 'Fidelity', 'category_code': None}

{'name': 'Quirk', 'category_code': None}

{'name': 'Skyrove', 'category_code': None}

{'name': 'Leechblock', 'category_code': None}

{'name': 'My Success Gateway', 'category_code': None}

{'name': 'RealNames', 'category_code': None}

{'name': 'The Easynet Group', 'category_code': None}

{'name': 'NetNames', 'category_code': None}

{'name': 'Sniperoo', 'category_code': None}

{'name': 'JD Project', 'category_code': None}

{'name': 'ABC News', 'category_code': None}

{'name': 'Teoma Technologies', 'category_code': None}

{'name': 'cometro', 'category_code': None}

{'name': 'U-Cast', 'category_code': None}

{'name': 'TechJuicer', 'category_code': None}

{'name': 'Fnatic', 'category_code': None}

{'name': 'Sports Gamer', 'category_code': None}

{'name': 'Infraworks', 'category_code': None}

{'name': 'MessageOne', 'category_code': None}

{'name': 'Idealab', 'category_code': None}

{'name': 'Invitastic', 'category_code': None}

{'name': 'Windows Live Events', 'category_code': None}

{'name': 'News Futures', 'category_code': None}

{'name': 'Foresight Exchange', 'category_code': None}

### 8. All the companies that have at least 100 employees but less than 1000. Retrieve only the `name` and `number of employees` fields.

In [98]:
for i,x in enumerate(db.companies.find(filter={'$and':[{'number_of_employees':{'$gte':100}},
                                                       {'number_of_employees':{'$lt':1000}}]},
                                       sort=[('number_of_employees',-1)],
                                       projection={'name':1,'_id':0,'number_of_employees':1})):
    if i<50:
        print(x,'\n')

{'name': 'Datamonitor', 'number_of_employees': 984}

{'name': 'Infinera Corporation', 'number_of_employees': 974}

{'name': 'Box', 'number_of_employees': 950}

{'name': 'NorthPoint Communications Group', 'number_of_employees': 948}

{'name': '888 Holdings', 'number_of_employees': 931}

{'name': 'Forrester Research', 'number_of_employees': 903}

{'name': 'Workday', 'number_of_employees': 900}

{'name': 'InMobi', 'number_of_employees': 900}

{'name': 'Relax Solutions Pvt Ltd', 'number_of_employees': 900}

{'name': 'SonicWALL', 'number_of_employees': 900}

{'name': 'Webmetrics', 'number_of_employees': 900}

{'name': 'Cornerstone OnDemand', 'number_of_employees': 881}

{'name': 'Yelp', 'number_of_employees': 800}

{'name': 'MySpace', 'number_of_employees': 800}

{'name': 'ZoomInfo', 'number_of_employees': 800}

{'name': 'Mozilla', 'number_of_employees': 800}

{'name': 'Buongiorno', 'number_of_employees': 800}

{'name': 'Cvent', 'number_of_employees': 800}

{'name': 'Wayfair', 'number_of_employees': 800}

{'name': 'BitDefender', 'number_of_employees': 800}

{'name': 'Gateway TechnoLabs Pvt Ltd', 'number_of_employees': 800}

{'name': 'LivingLink', 'number_of_employees': 800}

{'name': 'LivingLink', 'number_of_employees': 800}

{'name': 'Good Technology', 'number_of_employees': 800}

{'name': 'RightNow Technologies', 'number_of_employees': 800}

{'name': 'SourceMedia', 'number_of_employees': 800}

{'name': 'Pegasystems', 'number_of_employees': 750}

{'name': 'Landor Associates', 'number_of_employees': 750}

{'name': 'Intelligent Software Solutions', 'number_of_employees': 730}

{'name': 'Sonosite', 'number_of_employees': 715}

{'name': 'Criteo', 'number_of_employees': 700}

{'name': 'Citrix Online', 'number_of_employees': 700}

{'name': 'Toluna', 'number_of_employees': 700}

{'name': 'Barracuda Networks', 'number_of_employees': 700}

{'name': 'Creative Kingdom Animation Studios Film', 'number_of_employees': 700}

{'name': 'GREE', 'number_of_employees': 700}

{'name': 'TGS Geophysicl', 'number_of_employees': 696}

{'name': '4shared', 'number_of_employees': 666}

{'name': 'HubSpot', 'number_of_employees': 650}

{'name': 'Kabam', 'number_of_employees': 650}

{'name': 'Scope e Knowledge Center Pvt Ltd', 'number_of_employees': 650}

{'name': 'Silver Spring Networks', 'number_of_employees': 650}

{'name': 'SLR Consulting', 'number_of_employees': 650}

{'name': 'LifeLock', 'number_of_employees': 644}

{'name': 'Shutterfly', 'number_of_employees': 611}

{'name': 'AdventNet', 'number_of_employees': 600}

{'name': 'PhotoBox', 'number_of_employees': 600}

{'name': 'Bazaarvoice', 'number_of_employees': 600}

{'name': 'TechTarget', 'number_of_employees': 600}

{'name': 'Zillow', 'number_of_employees': 600}

### 9. Order all the companies by their IPO price descendently.

In [99]:
for i,x in enumerate(db.companies.find(filter={'ipo.valuation_amount':{'$gte':0}},
                                       sort=[('ipo.valuation_amount',-1)],
                                       projection={'name':1,'_id':0,'ipo.valuation_amount':1})):
    if i<50:
        print(x,'\n')

{'name': 'GREE', 'ipo': {'valuation_amount': 108960000000}}

{'name': 'Facebook', 'ipo': {'valuation_amount': 104000000000}}

{'name': 'Amazon', 'ipo': {'valuation_amount': 100000000000}}

{'name': 'Twitter', 'ipo': {'valuation_amount': 18100000000}}

{'name': 'Groupon', 'ipo': {'valuation_amount': 12800000000}}

{'name': 'Tencent', 'ipo': {'valuation_amount': 11000000000}}

{'name': 'Western Digital', 'ipo': {'valuation_amount': 9430000000}}

{'name': 'LinkedIn', 'ipo': {'valuation_amount': 9310000000}}

{'name': 'BMC Software', 'ipo': {'valuation_amount': 6000000000}}

{'name': 'Rackspace', 'ipo': {'valuation_amount': 5440000000}}

{'name': 'Baidu', 'ipo': {'valuation_amount': 4000000000}}

{'name': 'TripAdvisor', 'ipo': {'valuation_amount': 3273770000}}

{'name': 'HomeAway', 'ipo': {'valuation_amount': 3000000000}}

{'name': 'Zillow', 'ipo': {'valuation_amount': 2550000000}}

{'name': 'Nielsen', 'ipo': {'valuation_amount': 1600000000}}

{'name': 'Yelp', 'ipo': {'valuation_amount': 1300000000}}

{'name': 'Chegg', 'ipo': {'valuation_amount': 1100000000}}

{'name': 'Chegg', 'ipo': {'valuation_amount': 1100000000}}

{'name': 'RPX Corporation', 'ipo': {'valuation_amount': 1096000000}}

{'name': 'Higher One', 'ipo': {'valuation_amount': 1060000000}}

{'name': 'OpenTable', 'ipo': {'valuation_amount': 1050000000}}

{'name': 'Jive Software', 'ipo': {'valuation_amount': 1000000000}}

{'name': 'BrightSource Energy', 'ipo': {'valuation_amount': 1000000000}}

{'name': 'QlikTech', 'ipo': {'valuation_amount': 1000000000}}

{'name': 'Millennial Media', 'ipo': {'valuation_amount': 973500000}}

{'name': 'Mixi', 'ipo': {'valuation_amount': 970000000}}

{'name': 'Cornerstone OnDemand', 'ipo': {'valuation_amount': 900000000}}

{'name': 'Infoblox', 'ipo': {'valuation_amount': 824000000}}

{'name': 'SolarWinds', 'ipo': {'valuation_amount': 803000000}}

{'name': 'Wix', 'ipo': {'valuation_amount': 750000000}}

{'name': 'Marketo', 'ipo': {'valuation_amount': 465000000}}

{'name': 'Opsware', 'ipo': {'valuation_amount': 450000000}}

{'name': 'Emdeon', 'ipo': {'valuation_amount': 367350000}}

{'name': 'Shutterfly', 'ipo': {'valuation_amount': 350000000}}

{'name': 'Telenav', 'ipo': {'valuation_amount': 337000000}}

{'name': 'Rally Software', 'ipo': {'valuation_amount': 315000000}}

{'name': 'STR', 'ipo': {'valuation_amount': 300000000}}

{'name': 'Brightcove', 'ipo': {'valuation_amount': 290000000}}

{'name': 'ChannelAdvisor', 'ipo': {'valuation_amount': 287000000}}

{'name': 'Elster Group', 'ipo': {'valuation_amount': 275000000}}

{'name': 'DemandTec', 'ipo': {'valuation_amount': 245000000}}

{'name': 'KIT digital', 'ipo': {'valuation_amount': 235000000}}

{'name': 'Tudou', 'ipo': {'valuation_amount': 174000000}}

{'name': 'DivX', 'ipo': {'valuation_amount': 160000000}}

{'name': 'QuinStreet', 'ipo': {'valuation_amount': 140000000}}

{'name': 'Geeknet', 'ipo': {'valuation_amount': 134000000}}

{'name': 'Salesforce', 'ipo': {'valuation_amount': 110000000}}

{'name': 'JumpTV', 'ipo': {'valuation_amount': 100000000}}

{'name': 'EnerNOC', 'ipo': {'valuation_amount': 95500000}}

{'name': 'Meru Networks', 'ipo': {'valuation_amount': 66600000}}

### 10. Retrieve the 10 companies with more employees, order by the `number of employees`

In [100]:
for i,x in enumerate(db.companies.find(sort=[('number_of_employees',-1)], limit=(10),
                                       projection={'name':1,'_id':0,'number_of_employees':1})):
    if i<50:
        print(x,'\n')

{'name': 'Siemens', 'number_of_employees': 405000}

{'name': 'IBM', 'number_of_employees': 388000}

{'name': 'Toyota', 'number_of_employees': 320000}

{'name': 'PayPal', 'number_of_employees': 300000}

{'name': 'Nippon Telegraph and Telephone Corporation', 'number_of_employees': 227000}

{'name': 'Samsung Electronics', 'number_of_employees': 221726}

{'name': 'Accenture', 'number_of_employees': 205000}

{'name': 'Tata Consultancy Services', 'number_of_employees': 200300}

{'name': 'Flextronics International', 'number_of_employees': 200000}

{'name': 'Safeway', 'number_of_employees': 186000}

### 11. All the companies founded on the second semester of the year. Limit your search to 1000 companies.

In [101]:
for i,x in enumerate(db.companies.find(filter={'founded_month':{'$gte':7}}, limit=(1000),
                                       projection={'name':1,'_id':0,'founded_month':1})):
    if i<50:
        print(x,'\n')

{'name': 'Wetpaint', 'founded_month': 10}

{'name': 'Zoho', 'founded_month': 9}

{'name': 'Digg', 'founded_month': 10}

{'name': 'Omnidrive', 'founded_month': 11}

{'name': 'eBay', 'founded_month': 9}

{'name': 'Joost', 'founded_month': 10}

{'name': 'Plaxo', 'founded_month': 11}

{'name': 'Powerset', 'founded_month': 10}

{'name': 'Kyte', 'founded_month': 12}

{'name': 'Thoof', 'founded_month': 12}

{'name': 'Jingle Networks', 'founded_month': 9}

{'name': 'LifeLock', 'founded_month': 8}

{'name': 'Wesabe', 'founded_month': 12}

{'name': 'SmugMug', 'founded_month': 11}

{'name': 'Google', 'founded_month': 9}

{'name': 'Skype', 'founded_month': 8}

{'name': 'Pando Networks', 'founded_month': 7}

{'name': 'Ikan', 'founded_month': 12}

{'name': 'delicious', 'founded_month': 9}

{'name': 'AllPeers', 'founded_month': 8}

{'name': 'Wize', 'founded_month': 8}

{'name': 'SellABand', 'founded_month': 8}

{'name': 'iContact', 'founded_month': 7}

{'name': 'MeeVee', 'founded_month': 7}

{'name': 'blinkx', 'founded_month': 12}

{'name': 'Zlio', 'founded_month': 11}

{'name': 'Yelp', 'founded_month': 7}

{'name': 'Jaiku', 'founded_month': 7}

{'name': 'Yapta', 'founded_month': 7}

{'name': 'Fleck', 'founded_month': 11}

{'name': 'SideStep', 'founded_month': 11}

{'name': 'RockYou', 'founded_month': 11}

{'name': 'Instructables', 'founded_month': 8}

{'name': 'Netvibes', 'founded_month': 9}

{'name': 'Swivel', 'founded_month': 12}

{'name': 'Slide', 'founded_month': 8}

{'name': 'CrowdVine', 'founded_month': 8}

{'name': 'TheFind', 'founded_month': 10}

{'name': 'Sway', 'founded_month': 12}

{'name': 'CornerWorld', 'founded_month': 9}

{'name': 'FlickIM', 'founded_month': 12}

{'name': 'Terabitz', 'founded_month': 7}

{'name': 'Kaboodle', 'founded_month': 10}

{'name': 'GigaOM', 'founded_month': 7}

{'name': 'Redfin', 'founded_month': 10}

{'name': 'Wink', 'founded_month': 8}

{'name': 'Go2Web20', 'founded_month': 9}

{'name': 'TechnologyGuide', 'founded_month': 10}

{'name': 'Techmeme', 'founded_month': 10}

{'name': 'Ujogo', 'founded_month': 7}

### 12. All the companies that have been 'deadpooled' after the third year.

In [102]:
for i,x in enumerate(db.companies.find(filter={'$and':[{'$expr':{'$gt':['$deadpooled_year',
                                                                        {'$add':['$founded_year',3]}]}},
                                                       {'founded_year':{'$gte':0}}]},
                                       projection={'name':1,'_id':0,'deadpooled_year':1,'founded_year':1})):
    if i<50:
        print(x,'\n')

{'name': 'Babelgum', 'founded_year': 2007, 'deadpooled_year': 2013}

{'name': 'Thoof', 'founded_year': 2006, 'deadpooled_year': 2013}

{'name': 'Wesabe', 'founded_year': 2005, 'deadpooled_year': 2010}

{'name': 'Stickam', 'founded_year': 2006, 'deadpooled_year': 2013}

{'name': 'AllPeers', 'founded_year': 2004, 'deadpooled_year': 2008}

{'name': 'EQO', 'founded_year': 2006, 'deadpooled_year': 2012}

{'name': 'AllofMP3', 'founded_year': 2000, 'deadpooled_year': 2007}

{'name': 'SellABand', 'founded_year': 2006, 'deadpooled_year': 2010}

{'name': 'Zlio', 'founded_year': 2005, 'deadpooled_year': 2011}

{'name': 'Jaiku', 'founded_year': 2006, 'deadpooled_year': 2012}

{'name': 'Coghead', 'founded_year': 2003, 'deadpooled_year': 2009}

{'name': 'Swivel', 'founded_year': 2005, 'deadpooled_year': 2010}

{'name': 'Slide', 'founded_year': 2005, 'deadpooled_year': 2011}

{'name': 'Sway', 'founded_year': 2004, 'deadpooled_year': 2012}

{'name': 'coComment', 'founded_year': 2006, 'deadpooled_year': 2012}

{'name': 'Hotelicopter', 'founded_year': 2006, 'deadpooled_year': 2012}

{'name': 'Ujogo', 'founded_year': 2007, 'deadpooled_year': 2012}

{'name': 'PeerMe', 'founded_year': 2004, 'deadpooled_year': 2009}

{'name': 'Tangler', 'founded_year': 2006, 'deadpooled_year': 2012}

{'name': 'TalkPlus', 'founded_year': 2004, 'deadpooled_year': 2008}

{'name': 'PermissionTV', 'founded_year': 2005, 'deadpooled_year': 2012}

{'name': 'Nirvanix', 'founded_year': 2007, 'deadpooled_year': 2013}

{'name': 'Millsberry', 'founded_year': 2004, 'deadpooled_year': 2011}

{'name': 'Revver', 'founded_year': 2004, 'deadpooled_year': 2011}

{'name': 'Sampa', 'founded_year': 2005, 'deadpooled_year': 2009}

{'name': 'DanceJam', 'founded_year': 2007, 'deadpooled_year': 2011}

{'name': 'Brightkite', 'founded_year': 2007, 'deadpooled_year': 2011}

{'name': 'Zango', 'founded_year': 1999, 'deadpooled_year': 2009}

{'name': 'BitPass', 'founded_year': 2002, 'deadpooled_year': 2012}

{'name': 'SpiralFrog', 'founded_year': 2004, 'deadpooled_year': 2009}

{'name': 'Multiply', 'founded_year': 2003, 'deadpooled_year': 2013}

{'name': 'RampedMedia', 'founded_year': 2006, 'deadpooled_year': 2013}

{'name': 'Nemedia', 'founded_year': 2002, 'deadpooled_year': 2013}

{'name': 'Trutap', 'founded_year': 1989, 'deadpooled_year': 2009}

{'name': 'ITema', 'founded_year': 2007, 'deadpooled_year': 2011}

{'name': 'Orgoo', 'founded_year': 2005, 'deadpooled_year': 2013}

{'name': 'RatePoint', 'founded_year': 2006, 'deadpooled_year': 2012}

{'name': 'MuseStorm', 'founded_year': 2005, 'deadpooled_year': 2010}

{'name': 'Eons', 'founded_year': 2005, 'deadpooled_year': 2012}

{'name': 'Cuil', 'founded_year': 2005, 'deadpooled_year': 2010}

{'name': 'mEgo', 'founded_year': 2005, 'deadpooled_year': 2012}

{'name': 'StoryBlender', 'founded_year': 2005, 'deadpooled_year': 2012}

{'name': 'BroadClip', 'founded_year': 2006, 'deadpooled_year': 2012}

{'name': 'Goojet', 'founded_year': 2006, 'deadpooled_year': 2012}

{'name': 'Notemarks', 'founded_year': 2003, 'deadpooled_year': 2009}

{'name': 'mPortico', 'founded_year': 2006, 'deadpooled_year': 2012}

{'name': 'Grouply', 'founded_year': 2006, 'deadpooled_year': 2012}

{'name': 'PlanHQ', 'founded_year': 2007, 'deadpooled_year': 2013}

{'name': 'Youlicit', 'founded_year': 2006, 'deadpooled_year': 2010}

{'name': 'Mixaloo', 'founded_year': 2007, 'deadpooled_year': 2013}

### 13. All the companies founded before 2000 that have and acquisition amount of more than 10.000.000

In [103]:
for i,x in enumerate(db.companies.find(filter={'$and':[{'founded_year':{'$lt':2000}},
                                                       {'acquisition.price_amount':{'$gte':10000000}}]},
                                       sort=[('acquisition.price_amount',-1)],
                                       projection={'name':1,'_id':0,'founded_year':1,'acquisition.price_amount':1})):
    if i<50:
        print(x,'\n')

{'name': 'BEA Systems', 'founded_year': 1995, 'acquisition': {'price_amount': 8500000000}}

{'name': 'Navteq', 'founded_year': 1985, 'acquisition': {'price_amount': 8100000000}}

{'name': 'Sun Microsystems', 'founded_year': 1982, 'acquisition': {'price_amount': 7400000000}}

{'name': 'Pixar', 'founded_year': 1986, 'acquisition': {'price_amount': 7400000000}}

{'name': 'LSI', 'founded_year': 1980, 'acquisition': {'price_amount': 6600000000}}

{'name': 'National Semiconductor', 'founded_year': 1959, 'acquisition': {'price_amount': 6500000000}}

{'name': 'aQuantive', 'founded_year': 1997, 'acquisition': {'price_amount': 6400000000}}

{'name': 'Siebel Systems', 'founded_year': 1993, 'acquisition': {'price_amount': 5850000000}}

{'name': 'Sybase', 'founded_year': 1984, 'acquisition': {'price_amount': 5800000000}}

{'name': 'Affiliated Computer Services', 'founded_year': 1988, 'acquisition': {'price_amount': 5750000000}}

{'name': 'Sabre', 'founded_year': 1960, 'acquisition': {'price_amount': 4300000000}}

{'name': 'Netscape', 'founded_year': 1994, 'acquisition': {'price_amount': 4200000000}}

{'name': 'Marvel Entertainment', 'founded_year': 1988, 'acquisition': {'price_amount': 4000000000}}

{'name': 'Sterling Commerce', 'founded_year': 1975, 'acquisition': {'price_amount': 3900000000}}

{'name': 'NetLogic Microsystems', 'founded_year': 1995, 'acquisition': {'price_amount': 3700000000}}

{'name': 'Stiefel', 'founded_year': 1847, 'acquisition': {'price_amount': 3600000000}}

{'name': 'The Weather Channel', 'founded_year': 1982, 'acquisition': {'price_amount': 3500000000}}

{'name': 'Lotus Development Corporation', 'founded_year': 1982, 'acquisition': {'price_amount': 3500000000}}

{'name': 'Macromedia', 'founded_year': 1992, 'acquisition': {'price_amount': 3400000000}}

{'name': 'Qualcomm Atheros', 'founded_year': 1998, 'acquisition': {'price_amount': 3100000000}}

{'name': 'Foundry Networks', 'founded_year': 1996, 'acquisition': {'price_amount': 3000000000}}

{'name': 'Global Crossing', 'founded_year': 1997, 'acquisition': {'price_amount': 3000000000}}

{'name': 'Global Crossing', 'founded_year': 1997, 'acquisition': {'price_amount': 3000000000}}

{'name': 'GeoCities', 'founded_year': 1996, 'acquisition': {'price_amount': 2870000000}}

{'name': 'Berkeley Networks', 'founded_year': 1996, 'acquisition': {'price_amount': 2800000000}}

{'name': '3Com', 'founded_year': 1980, 'acquisition': {'price_amount': 2700000000}}

{'name': '3Com', 'founded_year': 1980, 'acquisition': {'price_amount': 2700000000}}

{'name': 'Novell', 'founded_year': 1979, 'acquisition': {'price_amount': 2200000000}}

{'name': 'Omniture', 'founded_year': 1996, 'acquisition': {'price_amount': 1800000000}}

{'name': 'Applied Systems', 'founded_year': 1980, 'acquisition': {'price_amount': 1800000000}}

{'name': 'Opsware', 'founded_year': 1999, 'acquisition': {'price_amount': 1600000000}}

{'name': 'PayPal', 'founded_year': 1998, 'acquisition': {'price_amount': 1500000000}}

{'name': 'Responsys', 'founded_year': 1998, 'acquisition': {'price_amount': 1500000000}}

{'name': 'RightNow Technologies', 'founded_year': 1997, 'acquisition': {'price_amount': 1500000000}}

{'name': 'Equallogic', 'founded_year': 1984, 'acquisition': {'price_amount': 1400000000}}

{'name': 'Vertafore', 'founded_year': 1969, 'acquisition': {'price_amount': 1400000000}}

{'name': 'Digitas', 'founded_year': 1980, 'acquisition': {'price_amount': 1300000000}}

{'name': 'Blue Coat Systems', 'founded_year': 1996, 'acquisition': {'price_amount': 1300000000}}

{'name': 'Kenexa', 'founded_year': 1987, 'acquisition': {'price_amount': 1300000000}}

{'name': 'Zappos', 'founded_year': 1999, 'acquisition': {'price_amount': 1200000000}}

{'name': 'SPSS', 'founded_year': 1968, 'acquisition': {'price_amount': 1200000000}}

{'name': 'DoubleClick', 'founded_year': 1996, 'acquisition': {'price_amount': 1100000000}}

{'name': 'MapQuest', 'founded_year': 1996, 'acquisition': {'price_amount': 1100000000}}

{'name': 'Lastminute', 'founded_year': 1998, 'acquisition': {'price_amount': 1008000000}}

{'name': 'Alibaba', 'founded_year': 1999, 'acquisition': {'price_amount': 1000000000}}

{'name': 'Centennial Communications Corp', 'founded_year': 1988, 'acquisition': {'price_amount': 944000000}}

{'name': 'Wind River', 'founded_year': 1981, 'acquisition': {'price_amount': 884000000}}

{'name': 'Eloqua', 'founded_year': 1999, 'acquisition': {'price_amount': 871000000}}

{'name': 'Sophos', 'founded_year': 1985, 'acquisition': {'price_amount': 830000000}}

{'name': 'Interwoven', 'founded_year': 1995, 'acquisition': {'price_amount': 775000000}}

### 14. All the companies that have been acquired after 2015, order by the acquisition amount, and retrieve only their `name` and `acquisiton` field.

In [104]:
for i,x in enumerate(db.companies.find(filter={'acquisition.acquired_year':{'$gt':2015}},
                                       sort=[('acquisition.price_amount',-1)],
                                       projection={'name':1,'_id':0,'acquisition.acquired_year':1})):
    if i<50:
        print(x,'\n')

### 15. Order the companies by their `founded year`, retrieving only their `name` and `founded year`.

In [111]:
db.companies.create_index([("founded_year", DESCENDING)])
for i,x in enumerate(db.companies.find(filter={'founded_year':{'$not':{'$eq':None}}},
                                       sort=[('founded_year',1)],
                                       projection={'name':1,'_id':0,'founded_year':1})):
    if i<50:
        print(x,'\n')

{'name': 'US Army', 'founded_year': 1800}

{'name': 'SmallWorlds', 'founded_year': 1800}

{'name': 'Alstrasoft', 'founded_year': 1800}

{'name': 'DuPont', 'founded_year': 1802}

{'name': 'Bachmann Industries', 'founded_year': 1833}

{'name': 'McKesson', 'founded_year': 1833}

{'name': 'Bertelsmann', 'founded_year': 1835}

{'name': 'Accuity', 'founded_year': 1836}

{'name': 'CENTRA', 'founded_year': 1839}

{'name': 'VideoSurf', 'founded_year': 1840}

{'name': 'VideoSurf', 'founded_year': 1840}

{'name': 'WeGame', 'founded_year': 1840}

{'name': 'The Economist Group', 'founded_year': 1843}

{'name': 'Pearson', 'founded_year': 1844}

{'name': 'Beloit College', 'founded_year': 1846}

{'name': 'Associated Press', 'founded_year': 1846}

{'name': 'Stiefel', 'founded_year': 1847}

{'name': 'Siemens', 'founded_year': 1847}

{'name': 'Pfizer', 'founded_year': 1848}

{'name': 'Corning', 'founded_year': 1851}

{'name': 'Nykredit Realkredit', 'founded_year': 1851}

{'name': 'Leucadia National', 'founded_year': 1854}

{'name': 'Louis Vuitton', 'founded_year': 1854}

{'name': 'The McClatchy Company', 'founded_year': 1857}

{'name': 'University of Washington', 'founded_year': 1861}

{'name': 'Athenix', 'founded_year': 1863}

{'name': 'Cornell University', 'founded_year': 1865}

{'name': 'Nokia', 'founded_year': 1865}

{'name': 'Millage, Inc', 'founded_year': 1867}

{'name': 'Scotts Miracle-Gro', 'founded_year': 1868}

{'name': 'La Nacion', 'founded_year': 1870}

{'name': 'SingTel', 'founded_year': 1879}

{'name': 'Chevron', 'founded_year': 1879}

{'name': 'University of Southern California', 'founded_year': 1880}

{'name': 'Elsevier', 'founded_year': 1880}

{'name': 'Los Angeles Times Media Group', 'founded_year': 1881}

{'name': 'Financial Models Co', 'founded_year': 1883}

{'name': 'Telenor', 'founded_year': 1885}

{'name': 'Bristol-Myers Squibb', 'founded_year': 1887}

{'name': 'McGraw-Hill Companies', 'founded_year': 1888}

{'name': 'Financial Times', 'founded_year': 1888}

{'name': 'National Geographic', 'founded_year': 1888}

{'name': 'Wall Street Journal', 'founded_year': 1889}

{'name': 'Nintendo', 'founded_year': 1889}

{'name': 'Harris', 'founded_year': 1890}

{'name': 'Teliasonera', 'founded_year': 1890}

{'name': 'General Electric', 'founded_year': 1890}

{'name': 'Cision', 'founded_year': 1892}

{'name': 'Waste Management', 'founded_year': 1894}

{'name': 'IBM', 'founded_year': 1896}

### 16. All the companies that have been founded on the first seven days of the month, including the seventh. Sort them by their `aquisition price` descendently. Limit the search to 10 documents.

In [72]:
for i,x in enumerate(db.companies.find(filter={'founded_day':{'$lte':7}},
                                       sort=[('acquisition.price_amount',-1)], limit=(10),
                                       projection={'name':1,'_id':0,'acquisition.price_amount':1,'founded_day':1})):
    if i<50:        
        print(x,'\n')

{'name': 'Netscape', 'founded_day': 4, 'acquisition': {'price_amount': 4200000000}}

{'name': 'PayPal', 'founded_day': 1, 'acquisition': {'price_amount': 1500000000}}

{'name': 'Zappos', 'founded_day': 1, 'acquisition': {'price_amount': 1200000000}}

{'name': 'Alibaba', 'founded_day': 1, 'acquisition': {'price_amount': 1000000000}}

{'name': 'Postini', 'founded_day': 2, 'acquisition': {'price_amount': 625000000}}

{'name': 'Danger', 'founded_day': 1, 'acquisition': {'price_amount': 500000000}}

{'name': 'Clearwell Systems', 'founded_day': 6, 'acquisition': {'price_amount': 410000000}}

{'name': 'PrimeSense', 'founded_day': 1, 'acquisition': {'price_amount': 345000000}}

{'name': 'Amobee', 'founded_day': 1, 'acquisition': {'price_amount': 321000000}}

{'name': 'BlueLithium', 'founded_day': 1, 'acquisition': {'price_amount': 300000000}}

### 17. All the companies on the 'web' `category` that have more than 4000 employees. Sort them by the amount of employees in ascendant order.

In [71]:
for i,x in enumerate(db.companies.find(filter={'$and':[{'category_code':{'$eq':'web'}},
                                                       {'number_of_employees':{'$gt':4000}}]},
                                       sort=[('number_of_employees',1)],
                                       projection={'name':1,'_id':0,'number_of_employees':1,'category_code':1})):
    if i<50:
        print(x,'\n')

{'name': 'Expedia', 'category_code': 'web', 'number_of_employees': 4400}

{'name': 'AOL', 'category_code': 'web', 'number_of_employees': 8000}

{'name': 'Webkinz', 'category_code': 'web', 'number_of_employees': 8657}

{'name': 'Rakuten', 'category_code': 'web', 'number_of_employees': 10000}

{'name': 'Los Angeles Times Media Group', 'category_code': 'web', 'number_of_employees': 10000}

{'name': 'Groupon', 'category_code': 'web', 'number_of_employees': 10000}

{'name': 'Yahoo!', 'category_code': 'web', 'number_of_employees': 13600}

{'name': 'eBay', 'category_code': 'web', 'number_of_employees': 15000}

{'name': 'Experian', 'category_code': 'web', 'number_of_employees': 15500}

### 18. All the companies which their acquisition amount is more than 10.000.000, and currency are 'EUR'.

In [68]:
for i,x in enumerate(db.companies.find(filter={'$and':[{'acquisition.price_amount':{'$gt':10000000}},
                                                       {'acquisition.price_currency_code':{'$eq':'EUR'}}]},
                                       projection={'name':1,'_id':0,'acquisition.price_amount':1,
                                                   'acquisition.price_currency_code':1})):
    if i<50:
        print(x,'\n')

{'name': 'ZYB', 'acquisition': {'price_amount': 31500000, 'price_currency_code': 'EUR'}}

{'name': 'Apertio', 'acquisition': {'price_amount': 140000000, 'price_currency_code': 'EUR'}}

{'name': 'Greenfield Online', 'acquisition': {'price_amount': 40000000, 'price_currency_code': 'EUR'}}

{'name': 'Webedia', 'acquisition': {'price_amount': 70000000, 'price_currency_code': 'EUR'}}

{'name': 'Wayfinder', 'acquisition': {'price_amount': 24000000, 'price_currency_code': 'EUR'}}

{'name': 'Tuenti Technologies', 'acquisition': {'price_amount': 70000000, 'price_currency_code': 'EUR'}}

{'name': 'BioMed Central', 'acquisition': {'price_amount': 43400000, 'price_currency_code': 'EUR'}}

### 19. All the companies that have been acquired on the first trimester of the year. Limit the search to 10 companies, and retrieve only their `name` and `acquisition` fields.

In [67]:
for i,x in enumerate(db.companies.find(filter={'acquisition.acquired_month':{'$lte':3}}, limit=(10),
                                       projection={'name':1,'_id':0,'acquisition.acquired_month':1})):
    if i<50:
        print(x,'\n')

{'name': 'Kyte', 'acquisition': {'acquired_month': 1}}

{'name': 'NetRatings', 'acquisition': {'acquired_month': 2}}

{'name': 'blogTV', 'acquisition': {'acquired_month': 3}}

{'name': 'Livestream', 'acquisition': {'acquired_month': 1}}

{'name': 'iContact', 'acquisition': {'acquired_month': 2}}

{'name': 'Coghead', 'acquisition': {'acquired_month': 2}}

{'name': 'Dailymotion', 'acquisition': {'acquired_month': 2}}

{'name': 'Netvibes', 'acquisition': {'acquired_month': 2}}

{'name': 'Flickr', 'acquisition': {'acquired_month': 3}}

{'name': 'BabyCenter', 'acquisition': {'acquired_month': 3}}

### 20. All the companies that have been founded between 2000 and 2010, but have not been acquired before 2011.

In [66]:
for i,x in enumerate(db.companies.find(filter={'$and':[{'founded_year':{'$gte':2000}},
                                                       {'founded_year':{'$lte':2010}},
                                                       {'acquisition.acquired_year':{'$not':{'$lt':2011}}}]},
                                       projection={'name':1,'_id':0,'founded_year':1,
                                                   'acquisition.acquired_year':1})):
    if i<50:
        print(x,'\n')

{'name': 'Wetpaint', 'founded_year': 2005, 'acquisition': {'acquired_year': 2013}}

{'name': 'Zoho', 'founded_year': 2005}

{'name': 'Digg', 'founded_year': 2004, 'acquisition': {'acquired_year': 2012}}

{'name': 'Facebook', 'founded_year': 2004}

{'name': 'Omnidrive', 'founded_year': 2005}

{'name': 'Geni', 'founded_year': 2006, 'acquisition': {'acquired_year': 2012}}

{'name': 'Twitter', 'founded_year': 2006}

{'name': 'Scribd', 'founded_year': 2007}

{'name': 'Slacker', 'founded_year': 2006}

{'name': 'MeetMoi', 'founded_year': 2007}

{'name': 'Babelgum', 'founded_year': 2007}

{'name': 'Technorati', 'founded_year': 2002}

{'name': 'AddThis', 'founded_year': 2004}

{'name': 'OpenX', 'founded_year': 2008}

{'name': 'Mahalo', 'founded_year': 2007}

{'name': 'Sparter', 'founded_year': 2007}

{'name': 'Kyte', 'founded_year': 2006, 'acquisition': {'acquired_year': 2011}}

{'name': 'Thoof', 'founded_year': 2006}

{'name': 'Jingle Networks', 'founded_year': 2005, 'acquisition': {'acquired_year': 2011}}

{'name': 'Meetup', 'founded_year': 2002}

{'name': 'LifeLock', 'founded_year': 2005}

{'name': 'Wesabe', 'founded_year': 2005}

{'name': 'Jangl SMS', 'founded_year': 2005}

{'name': 'SmugMug', 'founded_year': 2002}

{'name': 'Prosper', 'founded_year': 2006}

{'name': 'Stickam', 'founded_year': 2006}

{'name': 'blogTV', 'founded_year': 2006, 'acquisition': {'acquired_year': 2013}}

{'name': 'Ustream', 'founded_year': 2007}

{'name': 'AdaptiveBlue', 'founded_year': 2007}

{'name': 'Pando Networks', 'founded_year': 2004}

{'name': 'Ikan', 'founded_year': 2003}

{'name': 'delicious', 'founded_year': 2003, 'acquisition': {'acquired_year': 2011}}

{'name': 'Topix', 'founded_year': 2002}

{'name': 'Revision3', 'founded_year': 2005, 'acquisition': {'acquired_year': 2012}}

{'name': 'AllPeers', 'founded_year': 2004}

{'name': 'CriticalMetrics', 'founded_year': 2007}

{'name': 'ZenZui', 'founded_year': 2007}

{'name': 'SodaHead', 'founded_year': 2007}

{'name': 'EQO', 'founded_year': 2006}

{'name': 'AllofMP3', 'founded_year': 2000}

{'name': 'SellABand', 'founded_year': 2006}

{'name': 'Funny Or Die', 'founded_year': 2007}

{'name': 'Steorn', 'founded_year': 2000}

{'name': 'iContact', 'founded_year': 2003, 'acquisition': {'acquired_year': 2012}}

{'name': 'blinkx', 'founded_year': 2004}

{'name': 'Mashery', 'founded_year': 2006, 'acquisition': {'acquired_year': 2013}}

{'name': 'ClipBlast!', 'founded_year': 2005}

{'name': 'Zlio', 'founded_year': 2005}

{'name': 'Yelp', 'founded_year': 2004}

{'name': 'Spotplex', 'founded_year': 2007}